/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminAuditLogResponseSchema {
    #[serde(rename = "log_id")]
    pub log_id: String,
    #[serde(rename = "admin_user_id")]
    pub admin_user_id: String,
    #[serde(rename = "target_type")]
    pub target_type: String,
    /// The ID of the affected entity (user, channel, role, invite code, etc.)
    #[serde(rename = "target_id")]
    pub target_id: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "audit_log_reason", deserialize_with = "Option::deserialize")]
    pub audit_log_reason: Option<String>,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl AdminAuditLogResponseSchema {
    #[must_use] 
    pub fn new(
        log_id: String,
        admin_user_id: String,
        target_type: String,
        target_id: String,
        action: String,
        audit_log_reason: Option<String>,
        metadata: std::collections::HashMap<String, String>,
        created_at: String,
    ) -> AdminAuditLogResponseSchema {
        AdminAuditLogResponseSchema {
            log_id,
            admin_user_id,
            target_type,
            target_id,
            action,
            audit_log_reason,
            metadata,
            created_at,
        }
    }
}
