/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `ApiErrorCode` : Error codes returned by API operations
/// Error codes returned by API operations
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum ApiErrorCode {
    #[serde(rename = "ACCESS_DENIED")]
    #[default]
    AccessDenied,
    #[serde(rename = "ACCOUNT_DISABLED")]
    AccountDisabled,
    #[serde(rename = "BAD_GATEWAY")]
    BadGateway,
    #[serde(rename = "BAD_REQUEST")]
    BadRequest,
    #[serde(rename = "BLUESKY_OAUTH_AUTHORIZATION_FAILED")]
    BlueskyOauthAuthorizationFailed,
    #[serde(rename = "BLUESKY_OAUTH_CALLBACK_FAILED")]
    BlueskyOauthCallbackFailed,
    #[serde(rename = "BLUESKY_OAUTH_NOT_ENABLED")]
    BlueskyOauthNotEnabled,
    #[serde(rename = "BLUESKY_OAUTH_SESSION_EXPIRED")]
    BlueskyOauthSessionExpired,
    #[serde(rename = "BLUESKY_OAUTH_STATE_INVALID")]
    BlueskyOauthStateInvalid,
    #[serde(rename = "ACCOUNT_SCHEDULED_FOR_DELETION")]
    AccountScheduledForDeletion,
    #[serde(rename = "ACCOUNT_SUSPENDED_PERMANENTLY")]
    AccountSuspendedPermanently,
    #[serde(rename = "ACCOUNT_SUSPENDED_TEMPORARILY")]
    AccountSuspendedTemporarily,
    #[serde(rename = "ACCOUNT_SUSPICIOUS_ACTIVITY")]
    AccountSuspiciousActivity,
    #[serde(rename = "ACCOUNT_TOO_NEW_FOR_GUILD")]
    AccountTooNewForGuild,
    #[serde(rename = "ACLS_MUST_BE_NON_EMPTY")]
    AclsMustBeNonEmpty,
    #[serde(rename = "ADMIN_API_KEY_NOT_FOUND")]
    AdminApiKeyNotFound,
    #[serde(rename = "APPLICATION_NOT_FOUND")]
    ApplicationNotFound,
    #[serde(rename = "APPLICATION_NOT_OWNED")]
    ApplicationNotOwned,
    #[serde(rename = "ALREADY_FRIENDS")]
    AlreadyFriends,
    #[serde(rename = "AUDIT_LOG_INDEXING")]
    AuditLogIndexing,
    #[serde(rename = "BOTS_CANNOT_SEND_FRIEND_REQUESTS")]
    BotsCannotSendFriendRequests,
    #[serde(rename = "BOT_ALREADY_IN_GUILD")]
    BotAlreadyInGuild,
    #[serde(rename = "BOT_APPLICATION_NOT_FOUND")]
    BotApplicationNotFound,
    #[serde(rename = "BOT_IS_PRIVATE")]
    BotIsPrivate,
    #[serde(rename = "BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED")]
    BotUserAuthEndpointAccessDenied,
    #[serde(rename = "BOT_USER_AUTH_SESSION_CREATION_DENIED")]
    BotUserAuthSessionCreationDenied,
    #[serde(rename = "BOT_USER_GENERATION_FAILED")]
    BotUserGenerationFailed,
    #[serde(rename = "BOT_USER_NOT_FOUND")]
    BotUserNotFound,
    #[serde(rename = "CALL_ALREADY_EXISTS")]
    CallAlreadyExists,
    #[serde(rename = "CANNOT_EDIT_OTHER_USER_MESSAGE")]
    CannotEditOtherUserMessage,
    #[serde(rename = "CANNOT_EXECUTE_ON_DM")]
    CannotExecuteOnDm,
    #[serde(rename = "CANNOT_MODIFY_SYSTEM_WEBHOOK")]
    CannotModifySystemWebhook,
    #[serde(rename = "CANNOT_MODIFY_VOICE_STATE")]
    CannotModifyVoiceState,
    #[serde(rename = "CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY")]
    CannotRedeemPlutoniumWithVisionary,
    #[serde(rename = "CANNOT_REPORT_OWN_GUILD")]
    CannotReportOwnGuild,
    #[serde(rename = "CANNOT_REPORT_OWN_MESSAGE")]
    CannotReportOwnMessage,
    #[serde(rename = "CANNOT_REPORT_YOURSELF")]
    CannotReportYourself,
    #[serde(rename = "CANNOT_SEND_EMPTY_MESSAGE")]
    CannotSendEmptyMessage,
    #[serde(rename = "CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER")]
    CannotSendFriendRequestToBlockedUser,
    #[serde(rename = "CANNOT_SEND_FRIEND_REQUEST_TO_SELF")]
    CannotSendFriendRequestToSelf,
    #[serde(rename = "CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL")]
    CannotSendMessagesInNonTextChannel,
    #[serde(rename = "CANNOT_SEND_MESSAGES_TO_USER")]
    CannotSendMessagesToUser,
    #[serde(rename = "CANNOT_TRANSFER_OWNERSHIP_TO_BOT")]
    CannotTransferOwnershipToBot,
    #[serde(rename = "CANNOT_SHRINK_RESERVED_SLOTS")]
    CannotShrinkReservedSlots,
    #[serde(rename = "CAPTCHA_REQUIRED")]
    CaptchaRequired,
    #[serde(rename = "CHANNEL_INDEXING")]
    ChannelIndexing,
    #[serde(rename = "CHUNKED_UPLOAD_CHUNK_INDEX_OUT_OF_RANGE")]
    ChunkedUploadChunkIndexOutOfRange,
    #[serde(rename = "CHUNKED_UPLOAD_INCOMPLETE")]
    ChunkedUploadIncomplete,
    #[serde(rename = "CHUNKED_UPLOAD_NOT_FOUND")]
    ChunkedUploadNotFound,
    #[serde(rename = "CHUNKED_UPLOAD_NOT_OWNED")]
    ChunkedUploadNotOwned,
    #[serde(rename = "COMMUNICATION_DISABLED")]
    CommunicationDisabled,
    #[serde(rename = "CONNECTION_ALREADY_EXISTS")]
    ConnectionAlreadyExists,
    #[serde(rename = "CONNECTION_INITIATION_TOKEN_INVALID")]
    ConnectionInitiationTokenInvalid,
    #[serde(rename = "CONNECTION_INVALID_IDENTIFIER")]
    ConnectionInvalidIdentifier,
    #[serde(rename = "CONNECTION_INVALID_TYPE")]
    ConnectionInvalidType,
    #[serde(rename = "CONNECTION_LIMIT_REACHED")]
    ConnectionLimitReached,
    #[serde(rename = "CONNECTION_NOT_FOUND")]
    ConnectionNotFound,
    #[serde(rename = "CONNECTION_VERIFICATION_FAILED")]
    ConnectionVerificationFailed,
    #[serde(rename = "CONFLICT")]
    Conflict,
    #[serde(rename = "CONTENT_BLOCKED")]
    ContentBlocked,
    #[serde(rename = "CREATION_FAILED")]
    CreationFailed,
    #[serde(rename = "CSAM_SCAN_FAILED")]
    CsamScanFailed,
    #[serde(rename = "CSAM_SCAN_PARSE_ERROR")]
    CsamScanParseError,
    #[serde(rename = "CSAM_SCAN_SUBSCRIPTION_ERROR")]
    CsamScanSubscriptionError,
    #[serde(rename = "CSAM_SCAN_TIMEOUT")]
    CsamScanTimeout,
    #[serde(rename = "DECRYPTION_FAILED")]
    DecryptionFailed,
    #[serde(rename = "DELETION_FAILED")]
    DeletionFailed,
    #[serde(rename = "DISCOVERY_ALREADY_APPLIED")]
    DiscoveryAlreadyApplied,
    #[serde(rename = "DISCOVERY_APPLICATION_ALREADY_REVIEWED")]
    DiscoveryApplicationAlreadyReviewed,
    #[serde(rename = "DISCOVERY_APPLICATION_NOT_FOUND")]
    DiscoveryApplicationNotFound,
    #[serde(rename = "DISCOVERY_DESCRIPTION_REQUIRED")]
    DiscoveryDescriptionRequired,
    #[serde(rename = "DISCOVERY_DISABLED")]
    DiscoveryDisabled,
    #[serde(rename = "DISCOVERY_INSUFFICIENT_MEMBERS")]
    DiscoveryInsufficientMembers,
    #[serde(rename = "DISCOVERY_INVALID_CATEGORY")]
    DiscoveryInvalidCategory,
    #[serde(rename = "DISCOVERY_NOT_DISCOVERABLE")]
    DiscoveryNotDiscoverable,
    #[serde(rename = "DISCRIMINATOR_REQUIRED")]
    DiscriminatorRequired,
    #[serde(rename = "EMAIL_SERVICE_NOT_TESTABLE")]
    EmailServiceNotTestable,
    #[serde(rename = "EMAIL_VERIFICATION_REQUIRED")]
    EmailVerificationRequired,
    #[serde(rename = "EMPTY_ENCRYPTED_BODY")]
    EmptyEncryptedBody,
    #[serde(rename = "ENCRYPTION_FAILED")]
    EncryptionFailed,
    #[serde(rename = "EXPLICIT_CONTENT_CANNOT_BE_SENT")]
    ExplicitContentCannotBeSent,
    #[serde(rename = "FEATURE_NOT_AVAILABLE_SELF_HOSTED")]
    FeatureNotAvailableSelfHosted,
    #[serde(rename = "FEATURE_TEMPORARILY_DISABLED")]
    FeatureTemporarilyDisabled,
    #[serde(rename = "FILE_SIZE_TOO_LARGE")]
    FileSizeTooLarge,
    #[serde(rename = "FORBIDDEN")]
    Forbidden,
    #[serde(rename = "FRIEND_REQUEST_BLOCKED")]
    FriendRequestBlocked,
    #[serde(rename = "GATEWAY_TIMEOUT")]
    GatewayTimeout,
    #[serde(rename = "GENERAL_ERROR")]
    GeneralError,
    #[serde(rename = "GONE")]
    Gone,
    #[serde(rename = "GIFT_CODE_ALREADY_REDEEMED")]
    GiftCodeAlreadyRedeemed,
    #[serde(rename = "GUILD_PHONE_VERIFICATION_REQUIRED")]
    GuildPhoneVerificationRequired,
    #[serde(rename = "GUILD_VERIFICATION_REQUIRED")]
    GuildVerificationRequired,
    #[serde(rename = "HANDOFF_CODE_EXPIRED")]
    HandoffCodeExpired,
    #[serde(rename = "HARVEST_EXPIRED")]
    HarvestExpired,
    #[serde(rename = "HARVEST_FAILED")]
    HarvestFailed,
    #[serde(rename = "HARVEST_NOT_READY")]
    HarvestNotReady,
    #[serde(rename = "HARVEST_ON_COOLDOWN")]
    HarvestOnCooldown,
    #[serde(rename = "HTTP_GET_AUTHORIZE_NOT_SUPPORTED")]
    HttpGetAuthorizeNotSupported,
    #[serde(rename = "INSTANCE_VERSION_MISMATCH")]
    InstanceVersionMismatch,
    #[serde(rename = "INTERNAL_SERVER_ERROR")]
    InternalServerError,
    #[serde(rename = "INVALID_ACLS_FORMAT")]
    InvalidAclsFormat,
    #[serde(rename = "INVALID_API_ORIGIN")]
    InvalidApiOrigin,
    #[serde(rename = "INVALID_AUTH_TOKEN")]
    InvalidAuthToken,
    #[serde(rename = "INVALID_BOT_FLAG")]
    InvalidBotFlag,
    #[serde(rename = "INVALID_CAPTCHA")]
    InvalidCaptcha,
    #[serde(rename = "INVALID_CHANNEL_TYPE_FOR_CALL")]
    InvalidChannelTypeForCall,
    #[serde(rename = "INVALID_CHANNEL_TYPE")]
    InvalidChannelType,
    #[serde(rename = "INVALID_CLIENT")]
    InvalidClient,
    #[serde(rename = "INVALID_CLIENT_SECRET")]
    InvalidClientSecret,
    #[serde(rename = "INVALID_DSA_REPORT_TARGET")]
    InvalidDsaReportTarget,
    #[serde(rename = "INVALID_DSA_TICKET")]
    InvalidDsaTicket,
    #[serde(rename = "INVALID_DSA_VERIFICATION_CODE")]
    InvalidDsaVerificationCode,
    #[serde(rename = "INVALID_DECRYPTED_JSON")]
    InvalidDecryptedJson,
    #[serde(rename = "INVALID_EPHEMERAL_KEY")]
    InvalidEphemeralKey,
    #[serde(rename = "INVALID_FLAGS_FORMAT")]
    InvalidFlagsFormat,
    #[serde(rename = "INVALID_IV")]
    InvalidIv,
    #[serde(rename = "INVALID_FORM_BODY")]
    InvalidFormBody,
    #[serde(rename = "INVALID_GRANT")]
    InvalidGrant,
    #[serde(rename = "INVALID_HANDOFF_CODE")]
    InvalidHandoffCode,
    #[serde(rename = "INVALID_PACK_TYPE")]
    InvalidPackType,
    #[serde(rename = "INVALID_PERMISSIONS_INTEGER")]
    InvalidPermissionsInteger,
    #[serde(rename = "INVALID_PERMISSIONS_NEGATIVE")]
    InvalidPermissionsNegative,
    #[serde(rename = "INVALID_PHONE_NUMBER")]
    InvalidPhoneNumber,
    #[serde(rename = "INVALID_PHONE_VERIFICATION_CODE")]
    InvalidPhoneVerificationCode,
    #[serde(rename = "INVALID_REDIRECT_URI")]
    InvalidRedirectUri,
    #[serde(rename = "INVALID_REQUEST")]
    InvalidRequest,
    #[serde(rename = "INVALID_RESPONSE_TYPE_FOR_NON_BOT")]
    InvalidResponseTypeForNonBot,
    #[serde(rename = "INVALID_SCOPE")]
    InvalidScope,
    #[serde(rename = "INVALID_STREAM_KEY_FORMAT")]
    InvalidStreamKeyFormat,
    #[serde(rename = "INVALID_STREAM_THUMBNAIL_PAYLOAD")]
    InvalidStreamThumbnailPayload,
    #[serde(rename = "INVALID_SUDO_TOKEN")]
    InvalidSudoToken,
    #[serde(rename = "INVALID_SUSPICIOUS_FLAGS_FORMAT")]
    InvalidSuspiciousFlagsFormat,
    #[serde(rename = "INVALID_SYSTEM_FLAG")]
    InvalidSystemFlag,
    #[serde(rename = "INVALID_TIMESTAMP")]
    InvalidTimestamp,
    #[serde(rename = "INVALID_TOKEN")]
    InvalidToken,
    #[serde(rename = "INVALID_WEBAUTHN_AUTHENTICATION_COUNTER")]
    InvalidWebauthnAuthenticationCounter,
    #[serde(rename = "INVALID_WEBAUTHN_CREDENTIAL_COUNTER")]
    InvalidWebauthnCredentialCounter,
    #[serde(rename = "INVALID_WEBAUTHN_CREDENTIAL")]
    InvalidWebauthnCredential,
    #[serde(rename = "INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT")]
    InvalidWebauthnPublicKeyFormat,
    #[serde(rename = "INVITES_DISABLED")]
    InvitesDisabled,
    #[serde(rename = "IP_AUTHORIZATION_REQUIRED")]
    IpAuthorizationRequired,
    #[serde(rename = "IP_AUTHORIZATION_RESEND_COOLDOWN")]
    IpAuthorizationResendCooldown,
    #[serde(rename = "IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED")]
    IpAuthorizationResendLimitExceeded,
    #[serde(rename = "IP_BANNED")]
    IpBanned,
    #[serde(rename = "MAX_ANIMATED_EMOJIS")]
    MaxAnimatedEmojis,
    #[serde(rename = "MAX_BOOKMARKS")]
    MaxBookmarks,
    #[serde(rename = "MAX_CATEGORY_CHANNELS")]
    MaxCategoryChannels,
    #[serde(rename = "MAX_EMOJIS")]
    MaxEmojis,
    #[serde(rename = "MAX_FAVORITE_MEMES")]
    MaxFavoriteMemes,
    #[serde(rename = "MAX_FRIENDS")]
    MaxFriends,
    #[serde(rename = "MAX_GROUP_DM_RECIPIENTS")]
    MaxGroupDmRecipients,
    #[serde(rename = "MAX_GROUP_DMS")]
    MaxGroupDms,
    #[serde(rename = "MAX_GUILD_CHANNELS")]
    MaxGuildChannels,
    #[serde(rename = "MAX_GUILD_MEMBERS")]
    MaxGuildMembers,
    #[serde(rename = "MAX_GUILD_ROLES")]
    MaxGuildRoles,
    #[serde(rename = "MAX_GUILDS")]
    MaxGuilds,
    #[serde(rename = "MAX_INVITES")]
    MaxInvites,
    #[serde(rename = "MAX_PACK_EXPRESSIONS")]
    MaxPackExpressions,
    #[serde(rename = "MAX_PACKS")]
    MaxPacks,
    #[serde(rename = "MAX_PINS_PER_CHANNEL")]
    MaxPinsPerChannel,
    #[serde(rename = "MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE")]
    MessageTotalAttachmentSizeTooLarge,
    #[serde(rename = "MAX_REACTIONS")]
    MaxReactions,
    #[serde(rename = "MAX_STICKERS")]
    MaxStickers,
    #[serde(rename = "MAX_WEBHOOKS_PER_CHANNEL")]
    MaxWebhooksPerChannel,
    #[serde(rename = "MAX_WEBHOOKS_PER_GUILD")]
    MaxWebhooksPerGuild,
    #[serde(rename = "MAX_WEBHOOKS")]
    MaxWebhooks,
    #[serde(rename = "NCMEC_ALREADY_SUBMITTED")]
    NcmecAlreadySubmitted,
    #[serde(rename = "NCMEC_SUBMISSION_FAILED")]
    NcmecSubmissionFailed,
    #[serde(rename = "MEDIA_METADATA_ERROR")]
    MediaMetadataError,
    #[serde(rename = "METHOD_NOT_ALLOWED")]
    MethodNotAllowed,
    #[serde(rename = "MISSING_ACCESS")]
    MissingAccess,
    #[serde(rename = "MISSING_ACL")]
    MissingAcl,
    #[serde(rename = "MISSING_AUTHORIZATION")]
    MissingAuthorization,
    #[serde(rename = "MISSING_CLIENT_SECRET")]
    MissingClientSecret,
    #[serde(rename = "MISSING_EPHEMERAL_KEY")]
    MissingEphemeralKey,
    #[serde(rename = "MISSING_IV")]
    MissingIv,
    #[serde(rename = "MISSING_OAUTH_ADMIN_SCOPE")]
    MissingOauthAdminScope,
    #[serde(rename = "MISSING_OAUTH_FIELDS")]
    MissingOauthFields,
    #[serde(rename = "MISSING_OAUTH_SCOPE")]
    MissingOauthScope,
    #[serde(rename = "MISSING_PERMISSIONS")]
    MissingPermissions,
    #[serde(rename = "MISSING_REDIRECT_URI")]
    MissingRedirectUri,
    #[serde(rename = "NO_ACTIVE_CALL")]
    NoActiveCall,
    #[serde(rename = "NO_ACTIVE_SUBSCRIPTION")]
    NoActiveSubscription,
    #[serde(rename = "NOT_FOUND")]
    NotFound,
    #[serde(rename = "NOT_IMPLEMENTED")]
    NotImplemented,
    #[serde(rename = "NO_PASSKEYS_REGISTERED")]
    NoPasskeysRegistered,
    #[serde(rename = "NO_PENDING_DELETION")]
    NoPendingDeletion,
    #[serde(rename = "NO_USERS_WITH_FLUXERTAG_EXIST")]
    NoUsersWithFluxertagExist,
    #[serde(rename = "NO_VISIONARY_SLOTS_AVAILABLE")]
    NoVisionarySlotsAvailable,
    #[serde(rename = "NOT_A_BOT_APPLICATION")]
    NotABotApplication,
    #[serde(rename = "NOT_FRIENDS_WITH_USER")]
    NotFriendsWithUser,
    #[serde(rename = "NOT_OWNER_OF_ADMIN_API_KEY")]
    NotOwnerOfAdminApiKey,
    #[serde(rename = "NSFW_CONTENT_AGE_RESTRICTED")]
    NsfwContentAgeRestricted,
    #[serde(rename = "PACK_ACCESS_DENIED")]
    PackAccessDenied,
    #[serde(rename = "PASSKEY_AUTHENTICATION_FAILED")]
    PasskeyAuthenticationFailed,
    #[serde(rename = "PASSKEYS_DISABLED")]
    PasskeysDisabled,
    #[serde(rename = "PHONE_ALREADY_USED")]
    PhoneAlreadyUsed,
    #[serde(rename = "PHONE_RATE_LIMIT_EXCEEDED")]
    PhoneRateLimitExceeded,
    #[serde(rename = "PHONE_REQUIRED_FOR_SMS_MFA")]
    PhoneRequiredForSmsMfa,
    #[serde(rename = "PHONE_VERIFICATION_REQUIRED")]
    PhoneVerificationRequired,
    #[serde(rename = "PREMIUM_PURCHASE_BLOCKED")]
    PremiumPurchaseBlocked,
    #[serde(rename = "PREVIEW_MUST_BE_JPEG")]
    PreviewMustBeJpeg,
    #[serde(rename = "PROCESSING_FAILED")]
    ProcessingFailed,
    #[serde(rename = "RATE_LIMITED")]
    RateLimited,
    #[serde(rename = "REDIRECT_URI_REQUIRED_FOR_NON_BOT")]
    RedirectUriRequiredForNonBot,
    #[serde(rename = "REPORT_ALREADY_RESOLVED")]
    ReportAlreadyResolved,
    #[serde(rename = "REPORT_BANNED")]
    ReportBanned,
    #[serde(rename = "RESPONSE_VALIDATION_ERROR")]
    ResponseValidationError,
    #[serde(rename = "SERVICE_UNAVAILABLE")]
    ServiceUnavailable,
    #[serde(rename = "SESSION_TOKEN_MISMATCH")]
    SessionTokenMismatch,
    #[serde(rename = "SLOWMODE_RATE_LIMITED")]
    SlowmodeRateLimited,
    #[serde(rename = "SMS_MFA_NOT_ENABLED")]
    SmsMfaNotEnabled,
    #[serde(rename = "SMS_MFA_REQUIRES_TOTP")]
    SmsMfaRequiresTotp,
    #[serde(rename = "SMS_VERIFICATION_UNAVAILABLE")]
    SmsVerificationUnavailable,
    #[serde(rename = "SSO_REQUIRED")]
    SsoRequired,
    #[serde(rename = "STREAM_KEY_CHANNEL_MISMATCH")]
    StreamKeyChannelMismatch,
    #[serde(rename = "STREAM_KEY_SCOPE_MISMATCH")]
    StreamKeyScopeMismatch,
    #[serde(rename = "STREAM_THUMBNAIL_PAYLOAD_EMPTY")]
    StreamThumbnailPayloadEmpty,
    #[serde(rename = "STRIPE_ERROR")]
    StripeError,
    #[serde(rename = "STRIPE_GIFT_REDEMPTION_IN_PROGRESS")]
    StripeGiftRedemptionInProgress,
    #[serde(rename = "STRIPE_INVALID_PRODUCT")]
    StripeInvalidProduct,
    #[serde(rename = "STRIPE_INVALID_PRODUCT_CONFIGURATION")]
    StripeInvalidProductConfiguration,
    #[serde(rename = "STRIPE_NO_ACTIVE_SUBSCRIPTION")]
    StripeNoActiveSubscription,
    #[serde(rename = "STRIPE_NO_PURCHASE_HISTORY")]
    StripeNoPurchaseHistory,
    #[serde(rename = "STRIPE_NO_SUBSCRIPTION")]
    StripeNoSubscription,
    #[serde(rename = "STRIPE_PAYMENT_NOT_AVAILABLE")]
    StripePaymentNotAvailable,
    #[serde(rename = "STRIPE_SUBSCRIPTION_ALREADY_CANCELING")]
    StripeSubscriptionAlreadyCanceling,
    #[serde(rename = "STRIPE_SUBSCRIPTION_NOT_CANCELING")]
    StripeSubscriptionNotCanceling,
    #[serde(rename = "STRIPE_SUBSCRIPTION_PERIOD_END_MISSING")]
    StripeSubscriptionPeriodEndMissing,
    #[serde(rename = "STRIPE_WEBHOOK_NOT_AVAILABLE")]
    StripeWebhookNotAvailable,
    #[serde(rename = "STRIPE_WEBHOOK_SIGNATURE_INVALID")]
    StripeWebhookSignatureInvalid,
    #[serde(rename = "STRIPE_WEBHOOK_SIGNATURE_MISSING")]
    StripeWebhookSignatureMissing,
    #[serde(rename = "DONATION_AMOUNT_INVALID")]
    DonationAmountInvalid,
    #[serde(rename = "DONATION_MAGIC_LINK_EXPIRED")]
    DonationMagicLinkExpired,
    #[serde(rename = "DONATION_MAGIC_LINK_INVALID")]
    DonationMagicLinkInvalid,
    #[serde(rename = "DONATION_MAGIC_LINK_USED")]
    DonationMagicLinkUsed,
    #[serde(rename = "DONOR_NOT_FOUND")]
    DonorNotFound,
    #[serde(rename = "SUDO_MODE_REQUIRED")]
    SudoModeRequired,
    #[serde(rename = "TAG_ALREADY_TAKEN")]
    TagAlreadyTaken,
    #[serde(rename = "TEMPORARY_INVITE_REQUIRES_PRESENCE")]
    TemporaryInviteRequiresPresence,
    #[serde(rename = "TEST_HARNESS_DISABLED")]
    TestHarnessDisabled,
    #[serde(rename = "TEST_HARNESS_FORBIDDEN")]
    TestHarnessForbidden,
    #[serde(rename = "TWO_FA_NOT_ENABLED")]
    TwoFaNotEnabled,
    #[serde(rename = "TWO_FACTOR_REQUIRED")]
    TwoFactorRequired,
    #[serde(rename = "UNAUTHORIZED")]
    Unauthorized,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS")]
    UnclaimedAccountCannotAcceptFriendRequests,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS")]
    UnclaimedAccountCannotAddReactions,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS")]
    UnclaimedAccountCannotCreateApplications,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS")]
    UnclaimedAccountCannotJoinGroupDms,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS")]
    UnclaimedAccountCannotJoinOneOnOneVoiceCalls,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS")]
    UnclaimedAccountCannotJoinVoiceChannels,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES")]
    UnclaimedAccountCannotMakePurchases,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES")]
    UnclaimedAccountCannotSendDirectMessages,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS")]
    UnclaimedAccountCannotSendFriendRequests,
    #[serde(rename = "UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES")]
    UnclaimedAccountCannotSendMessages,
    #[serde(rename = "UNKNOWN_CHANNEL")]
    UnknownChannel,
    #[serde(rename = "UNKNOWN_EMOJI")]
    UnknownEmoji,
    #[serde(rename = "UNKNOWN_FAVORITE_MEME")]
    UnknownFavoriteMeme,
    #[serde(rename = "UNKNOWN_GIFT_CODE")]
    UnknownGiftCode,
    #[serde(rename = "UNKNOWN_GUILD")]
    UnknownGuild,
    #[serde(rename = "UNKNOWN_HARVEST")]
    UnknownHarvest,
    #[serde(rename = "UNKNOWN_INVITE")]
    UnknownInvite,
    #[serde(rename = "UNKNOWN_MEMBER")]
    UnknownMember,
    #[serde(rename = "UNKNOWN_MESSAGE")]
    UnknownMessage,
    #[serde(rename = "UNKNOWN_PACK")]
    UnknownPack,
    #[serde(rename = "UNKNOWN_REPORT")]
    UnknownReport,
    #[serde(rename = "UNKNOWN_ROLE")]
    UnknownRole,
    #[serde(rename = "UNKNOWN_STICKER")]
    UnknownSticker,
    #[serde(rename = "UNKNOWN_SUSPICIOUS_FLAG")]
    UnknownSuspiciousFlag,
    #[serde(rename = "UNKNOWN_USER_FLAG")]
    UnknownUserFlag,
    #[serde(rename = "UNKNOWN_USER")]
    UnknownUser,
    #[serde(rename = "UNKNOWN_VOICE_REGION")]
    UnknownVoiceRegion,
    #[serde(rename = "UNKNOWN_VOICE_SERVER")]
    UnknownVoiceServer,
    #[serde(rename = "UNKNOWN_WEBAUTHN_CREDENTIAL")]
    UnknownWebauthnCredential,
    #[serde(rename = "UNKNOWN_APPLICATION")]
    UnknownApplication,
    #[serde(rename = "UNKNOWN_WEBHOOK")]
    UnknownWebhook,
    #[serde(rename = "UNSUPPORTED_RESPONSE_TYPE")]
    UnsupportedResponseType,
    #[serde(rename = "USERNAME_NOT_AVAILABLE")]
    UsernameNotAvailable,
    #[serde(rename = "UPDATE_FAILED")]
    UpdateFailed,
    #[serde(rename = "USER_BANNED_FROM_GUILD")]
    UserBannedFromGuild,
    #[serde(rename = "USER_IP_BANNED_FROM_GUILD")]
    UserIpBannedFromGuild,
    #[serde(rename = "USER_NOT_IN_VOICE")]
    UserNotInVoice,
    #[serde(rename = "USER_OWNS_GUILDS")]
    UserOwnsGuilds,
    #[serde(rename = "VALIDATION_ERROR")]
    ValidationError,
    #[serde(rename = "VOICE_CHANNEL_FULL")]
    VoiceChannelFull,
    #[serde(rename = "WEBAUTHN_CREDENTIAL_LIMIT_REACHED")]
    WebauthnCredentialLimitReached,
}

impl std::fmt::Display for ApiErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccessDenied => write!(f, "ACCESS_DENIED"),
            Self::AccountDisabled => write!(f, "ACCOUNT_DISABLED"),
            Self::BadGateway => write!(f, "BAD_GATEWAY"),
            Self::BadRequest => write!(f, "BAD_REQUEST"),
            Self::BlueskyOauthAuthorizationFailed => {
                write!(f, "BLUESKY_OAUTH_AUTHORIZATION_FAILED")
            }
            Self::BlueskyOauthCallbackFailed => write!(f, "BLUESKY_OAUTH_CALLBACK_FAILED"),
            Self::BlueskyOauthNotEnabled => write!(f, "BLUESKY_OAUTH_NOT_ENABLED"),
            Self::BlueskyOauthSessionExpired => write!(f, "BLUESKY_OAUTH_SESSION_EXPIRED"),
            Self::BlueskyOauthStateInvalid => write!(f, "BLUESKY_OAUTH_STATE_INVALID"),
            Self::AccountScheduledForDeletion => write!(f, "ACCOUNT_SCHEDULED_FOR_DELETION"),
            Self::AccountSuspendedPermanently => write!(f, "ACCOUNT_SUSPENDED_PERMANENTLY"),
            Self::AccountSuspendedTemporarily => write!(f, "ACCOUNT_SUSPENDED_TEMPORARILY"),
            Self::AccountSuspiciousActivity => write!(f, "ACCOUNT_SUSPICIOUS_ACTIVITY"),
            Self::AccountTooNewForGuild => write!(f, "ACCOUNT_TOO_NEW_FOR_GUILD"),
            Self::AclsMustBeNonEmpty => write!(f, "ACLS_MUST_BE_NON_EMPTY"),
            Self::AdminApiKeyNotFound => write!(f, "ADMIN_API_KEY_NOT_FOUND"),
            Self::ApplicationNotFound => write!(f, "APPLICATION_NOT_FOUND"),
            Self::ApplicationNotOwned => write!(f, "APPLICATION_NOT_OWNED"),
            Self::AlreadyFriends => write!(f, "ALREADY_FRIENDS"),
            Self::AuditLogIndexing => write!(f, "AUDIT_LOG_INDEXING"),
            Self::BotsCannotSendFriendRequests => write!(f, "BOTS_CANNOT_SEND_FRIEND_REQUESTS"),
            Self::BotAlreadyInGuild => write!(f, "BOT_ALREADY_IN_GUILD"),
            Self::BotApplicationNotFound => write!(f, "BOT_APPLICATION_NOT_FOUND"),
            Self::BotIsPrivate => write!(f, "BOT_IS_PRIVATE"),
            Self::BotUserAuthEndpointAccessDenied => {
                write!(f, "BOT_USER_AUTH_ENDPOINT_ACCESS_DENIED")
            }
            Self::BotUserAuthSessionCreationDenied => {
                write!(f, "BOT_USER_AUTH_SESSION_CREATION_DENIED")
            }
            Self::BotUserGenerationFailed => write!(f, "BOT_USER_GENERATION_FAILED"),
            Self::BotUserNotFound => write!(f, "BOT_USER_NOT_FOUND"),
            Self::CallAlreadyExists => write!(f, "CALL_ALREADY_EXISTS"),
            Self::CannotEditOtherUserMessage => write!(f, "CANNOT_EDIT_OTHER_USER_MESSAGE"),
            Self::CannotExecuteOnDm => write!(f, "CANNOT_EXECUTE_ON_DM"),
            Self::CannotModifySystemWebhook => write!(f, "CANNOT_MODIFY_SYSTEM_WEBHOOK"),
            Self::CannotModifyVoiceState => write!(f, "CANNOT_MODIFY_VOICE_STATE"),
            Self::CannotRedeemPlutoniumWithVisionary => {
                write!(f, "CANNOT_REDEEM_PLUTONIUM_WITH_VISIONARY")
            }
            Self::CannotReportOwnGuild => write!(f, "CANNOT_REPORT_OWN_GUILD"),
            Self::CannotReportOwnMessage => write!(f, "CANNOT_REPORT_OWN_MESSAGE"),
            Self::CannotReportYourself => write!(f, "CANNOT_REPORT_YOURSELF"),
            Self::CannotSendEmptyMessage => write!(f, "CANNOT_SEND_EMPTY_MESSAGE"),
            Self::CannotSendFriendRequestToBlockedUser => {
                write!(f, "CANNOT_SEND_FRIEND_REQUEST_TO_BLOCKED_USER")
            }
            Self::CannotSendFriendRequestToSelf => write!(f, "CANNOT_SEND_FRIEND_REQUEST_TO_SELF"),
            Self::CannotSendMessagesInNonTextChannel => {
                write!(f, "CANNOT_SEND_MESSAGES_IN_NON_TEXT_CHANNEL")
            }
            Self::CannotSendMessagesToUser => write!(f, "CANNOT_SEND_MESSAGES_TO_USER"),
            Self::CannotTransferOwnershipToBot => write!(f, "CANNOT_TRANSFER_OWNERSHIP_TO_BOT"),
            Self::CannotShrinkReservedSlots => write!(f, "CANNOT_SHRINK_RESERVED_SLOTS"),
            Self::CaptchaRequired => write!(f, "CAPTCHA_REQUIRED"),
            Self::ChannelIndexing => write!(f, "CHANNEL_INDEXING"),
            Self::ChunkedUploadChunkIndexOutOfRange => {
                write!(f, "CHUNKED_UPLOAD_CHUNK_INDEX_OUT_OF_RANGE")
            }
            Self::ChunkedUploadIncomplete => write!(f, "CHUNKED_UPLOAD_INCOMPLETE"),
            Self::ChunkedUploadNotFound => write!(f, "CHUNKED_UPLOAD_NOT_FOUND"),
            Self::ChunkedUploadNotOwned => write!(f, "CHUNKED_UPLOAD_NOT_OWNED"),
            Self::CommunicationDisabled => write!(f, "COMMUNICATION_DISABLED"),
            Self::ConnectionAlreadyExists => write!(f, "CONNECTION_ALREADY_EXISTS"),
            Self::ConnectionInitiationTokenInvalid => {
                write!(f, "CONNECTION_INITIATION_TOKEN_INVALID")
            }
            Self::ConnectionInvalidIdentifier => write!(f, "CONNECTION_INVALID_IDENTIFIER"),
            Self::ConnectionInvalidType => write!(f, "CONNECTION_INVALID_TYPE"),
            Self::ConnectionLimitReached => write!(f, "CONNECTION_LIMIT_REACHED"),
            Self::ConnectionNotFound => write!(f, "CONNECTION_NOT_FOUND"),
            Self::ConnectionVerificationFailed => write!(f, "CONNECTION_VERIFICATION_FAILED"),
            Self::Conflict => write!(f, "CONFLICT"),
            Self::ContentBlocked => write!(f, "CONTENT_BLOCKED"),
            Self::CreationFailed => write!(f, "CREATION_FAILED"),
            Self::CsamScanFailed => write!(f, "CSAM_SCAN_FAILED"),
            Self::CsamScanParseError => write!(f, "CSAM_SCAN_PARSE_ERROR"),
            Self::CsamScanSubscriptionError => write!(f, "CSAM_SCAN_SUBSCRIPTION_ERROR"),
            Self::CsamScanTimeout => write!(f, "CSAM_SCAN_TIMEOUT"),
            Self::DecryptionFailed => write!(f, "DECRYPTION_FAILED"),
            Self::DeletionFailed => write!(f, "DELETION_FAILED"),
            Self::DiscoveryAlreadyApplied => write!(f, "DISCOVERY_ALREADY_APPLIED"),
            Self::DiscoveryApplicationAlreadyReviewed => {
                write!(f, "DISCOVERY_APPLICATION_ALREADY_REVIEWED")
            }
            Self::DiscoveryApplicationNotFound => write!(f, "DISCOVERY_APPLICATION_NOT_FOUND"),
            Self::DiscoveryDescriptionRequired => write!(f, "DISCOVERY_DESCRIPTION_REQUIRED"),
            Self::DiscoveryDisabled => write!(f, "DISCOVERY_DISABLED"),
            Self::DiscoveryInsufficientMembers => write!(f, "DISCOVERY_INSUFFICIENT_MEMBERS"),
            Self::DiscoveryInvalidCategory => write!(f, "DISCOVERY_INVALID_CATEGORY"),
            Self::DiscoveryNotDiscoverable => write!(f, "DISCOVERY_NOT_DISCOVERABLE"),
            Self::DiscriminatorRequired => write!(f, "DISCRIMINATOR_REQUIRED"),
            Self::EmailServiceNotTestable => write!(f, "EMAIL_SERVICE_NOT_TESTABLE"),
            Self::EmailVerificationRequired => write!(f, "EMAIL_VERIFICATION_REQUIRED"),
            Self::EmptyEncryptedBody => write!(f, "EMPTY_ENCRYPTED_BODY"),
            Self::EncryptionFailed => write!(f, "ENCRYPTION_FAILED"),
            Self::ExplicitContentCannotBeSent => write!(f, "EXPLICIT_CONTENT_CANNOT_BE_SENT"),
            Self::FeatureNotAvailableSelfHosted => write!(f, "FEATURE_NOT_AVAILABLE_SELF_HOSTED"),
            Self::FeatureTemporarilyDisabled => write!(f, "FEATURE_TEMPORARILY_DISABLED"),
            Self::FileSizeTooLarge => write!(f, "FILE_SIZE_TOO_LARGE"),
            Self::Forbidden => write!(f, "FORBIDDEN"),
            Self::FriendRequestBlocked => write!(f, "FRIEND_REQUEST_BLOCKED"),
            Self::GatewayTimeout => write!(f, "GATEWAY_TIMEOUT"),
            Self::GeneralError => write!(f, "GENERAL_ERROR"),
            Self::Gone => write!(f, "GONE"),
            Self::GiftCodeAlreadyRedeemed => write!(f, "GIFT_CODE_ALREADY_REDEEMED"),
            Self::GuildPhoneVerificationRequired => write!(f, "GUILD_PHONE_VERIFICATION_REQUIRED"),
            Self::GuildVerificationRequired => write!(f, "GUILD_VERIFICATION_REQUIRED"),
            Self::HandoffCodeExpired => write!(f, "HANDOFF_CODE_EXPIRED"),
            Self::HarvestExpired => write!(f, "HARVEST_EXPIRED"),
            Self::HarvestFailed => write!(f, "HARVEST_FAILED"),
            Self::HarvestNotReady => write!(f, "HARVEST_NOT_READY"),
            Self::HarvestOnCooldown => write!(f, "HARVEST_ON_COOLDOWN"),
            Self::HttpGetAuthorizeNotSupported => write!(f, "HTTP_GET_AUTHORIZE_NOT_SUPPORTED"),
            Self::InstanceVersionMismatch => write!(f, "INSTANCE_VERSION_MISMATCH"),
            Self::InternalServerError => write!(f, "INTERNAL_SERVER_ERROR"),
            Self::InvalidAclsFormat => write!(f, "INVALID_ACLS_FORMAT"),
            Self::InvalidApiOrigin => write!(f, "INVALID_API_ORIGIN"),
            Self::InvalidAuthToken => write!(f, "INVALID_AUTH_TOKEN"),
            Self::InvalidBotFlag => write!(f, "INVALID_BOT_FLAG"),
            Self::InvalidCaptcha => write!(f, "INVALID_CAPTCHA"),
            Self::InvalidChannelTypeForCall => write!(f, "INVALID_CHANNEL_TYPE_FOR_CALL"),
            Self::InvalidChannelType => write!(f, "INVALID_CHANNEL_TYPE"),
            Self::InvalidClient => write!(f, "INVALID_CLIENT"),
            Self::InvalidClientSecret => write!(f, "INVALID_CLIENT_SECRET"),
            Self::InvalidDsaReportTarget => write!(f, "INVALID_DSA_REPORT_TARGET"),
            Self::InvalidDsaTicket => write!(f, "INVALID_DSA_TICKET"),
            Self::InvalidDsaVerificationCode => write!(f, "INVALID_DSA_VERIFICATION_CODE"),
            Self::InvalidDecryptedJson => write!(f, "INVALID_DECRYPTED_JSON"),
            Self::InvalidEphemeralKey => write!(f, "INVALID_EPHEMERAL_KEY"),
            Self::InvalidFlagsFormat => write!(f, "INVALID_FLAGS_FORMAT"),
            Self::InvalidIv => write!(f, "INVALID_IV"),
            Self::InvalidFormBody => write!(f, "INVALID_FORM_BODY"),
            Self::InvalidGrant => write!(f, "INVALID_GRANT"),
            Self::InvalidHandoffCode => write!(f, "INVALID_HANDOFF_CODE"),
            Self::InvalidPackType => write!(f, "INVALID_PACK_TYPE"),
            Self::InvalidPermissionsInteger => write!(f, "INVALID_PERMISSIONS_INTEGER"),
            Self::InvalidPermissionsNegative => write!(f, "INVALID_PERMISSIONS_NEGATIVE"),
            Self::InvalidPhoneNumber => write!(f, "INVALID_PHONE_NUMBER"),
            Self::InvalidPhoneVerificationCode => write!(f, "INVALID_PHONE_VERIFICATION_CODE"),
            Self::InvalidRedirectUri => write!(f, "INVALID_REDIRECT_URI"),
            Self::InvalidRequest => write!(f, "INVALID_REQUEST"),
            Self::InvalidResponseTypeForNonBot => write!(f, "INVALID_RESPONSE_TYPE_FOR_NON_BOT"),
            Self::InvalidScope => write!(f, "INVALID_SCOPE"),
            Self::InvalidStreamKeyFormat => write!(f, "INVALID_STREAM_KEY_FORMAT"),
            Self::InvalidStreamThumbnailPayload => write!(f, "INVALID_STREAM_THUMBNAIL_PAYLOAD"),
            Self::InvalidSudoToken => write!(f, "INVALID_SUDO_TOKEN"),
            Self::InvalidSuspiciousFlagsFormat => write!(f, "INVALID_SUSPICIOUS_FLAGS_FORMAT"),
            Self::InvalidSystemFlag => write!(f, "INVALID_SYSTEM_FLAG"),
            Self::InvalidTimestamp => write!(f, "INVALID_TIMESTAMP"),
            Self::InvalidToken => write!(f, "INVALID_TOKEN"),
            Self::InvalidWebauthnAuthenticationCounter => {
                write!(f, "INVALID_WEBAUTHN_AUTHENTICATION_COUNTER")
            }
            Self::InvalidWebauthnCredentialCounter => {
                write!(f, "INVALID_WEBAUTHN_CREDENTIAL_COUNTER")
            }
            Self::InvalidWebauthnCredential => write!(f, "INVALID_WEBAUTHN_CREDENTIAL"),
            Self::InvalidWebauthnPublicKeyFormat => write!(f, "INVALID_WEBAUTHN_PUBLIC_KEY_FORMAT"),
            Self::InvitesDisabled => write!(f, "INVITES_DISABLED"),
            Self::IpAuthorizationRequired => write!(f, "IP_AUTHORIZATION_REQUIRED"),
            Self::IpAuthorizationResendCooldown => write!(f, "IP_AUTHORIZATION_RESEND_COOLDOWN"),
            Self::IpAuthorizationResendLimitExceeded => {
                write!(f, "IP_AUTHORIZATION_RESEND_LIMIT_EXCEEDED")
            }
            Self::IpBanned => write!(f, "IP_BANNED"),
            Self::MaxAnimatedEmojis => write!(f, "MAX_ANIMATED_EMOJIS"),
            Self::MaxBookmarks => write!(f, "MAX_BOOKMARKS"),
            Self::MaxCategoryChannels => write!(f, "MAX_CATEGORY_CHANNELS"),
            Self::MaxEmojis => write!(f, "MAX_EMOJIS"),
            Self::MaxFavoriteMemes => write!(f, "MAX_FAVORITE_MEMES"),
            Self::MaxFriends => write!(f, "MAX_FRIENDS"),
            Self::MaxGroupDmRecipients => write!(f, "MAX_GROUP_DM_RECIPIENTS"),
            Self::MaxGroupDms => write!(f, "MAX_GROUP_DMS"),
            Self::MaxGuildChannels => write!(f, "MAX_GUILD_CHANNELS"),
            Self::MaxGuildMembers => write!(f, "MAX_GUILD_MEMBERS"),
            Self::MaxGuildRoles => write!(f, "MAX_GUILD_ROLES"),
            Self::MaxGuilds => write!(f, "MAX_GUILDS"),
            Self::MaxInvites => write!(f, "MAX_INVITES"),
            Self::MaxPackExpressions => write!(f, "MAX_PACK_EXPRESSIONS"),
            Self::MaxPacks => write!(f, "MAX_PACKS"),
            Self::MaxPinsPerChannel => write!(f, "MAX_PINS_PER_CHANNEL"),
            Self::MessageTotalAttachmentSizeTooLarge => {
                write!(f, "MESSAGE_TOTAL_ATTACHMENT_SIZE_TOO_LARGE")
            }
            Self::MaxReactions => write!(f, "MAX_REACTIONS"),
            Self::MaxStickers => write!(f, "MAX_STICKERS"),
            Self::MaxWebhooksPerChannel => write!(f, "MAX_WEBHOOKS_PER_CHANNEL"),
            Self::MaxWebhooksPerGuild => write!(f, "MAX_WEBHOOKS_PER_GUILD"),
            Self::MaxWebhooks => write!(f, "MAX_WEBHOOKS"),
            Self::NcmecAlreadySubmitted => write!(f, "NCMEC_ALREADY_SUBMITTED"),
            Self::NcmecSubmissionFailed => write!(f, "NCMEC_SUBMISSION_FAILED"),
            Self::MediaMetadataError => write!(f, "MEDIA_METADATA_ERROR"),
            Self::MethodNotAllowed => write!(f, "METHOD_NOT_ALLOWED"),
            Self::MissingAccess => write!(f, "MISSING_ACCESS"),
            Self::MissingAcl => write!(f, "MISSING_ACL"),
            Self::MissingAuthorization => write!(f, "MISSING_AUTHORIZATION"),
            Self::MissingClientSecret => write!(f, "MISSING_CLIENT_SECRET"),
            Self::MissingEphemeralKey => write!(f, "MISSING_EPHEMERAL_KEY"),
            Self::MissingIv => write!(f, "MISSING_IV"),
            Self::MissingOauthAdminScope => write!(f, "MISSING_OAUTH_ADMIN_SCOPE"),
            Self::MissingOauthFields => write!(f, "MISSING_OAUTH_FIELDS"),
            Self::MissingOauthScope => write!(f, "MISSING_OAUTH_SCOPE"),
            Self::MissingPermissions => write!(f, "MISSING_PERMISSIONS"),
            Self::MissingRedirectUri => write!(f, "MISSING_REDIRECT_URI"),
            Self::NoActiveCall => write!(f, "NO_ACTIVE_CALL"),
            Self::NoActiveSubscription => write!(f, "NO_ACTIVE_SUBSCRIPTION"),
            Self::NotFound => write!(f, "NOT_FOUND"),
            Self::NotImplemented => write!(f, "NOT_IMPLEMENTED"),
            Self::NoPasskeysRegistered => write!(f, "NO_PASSKEYS_REGISTERED"),
            Self::NoPendingDeletion => write!(f, "NO_PENDING_DELETION"),
            Self::NoUsersWithFluxertagExist => write!(f, "NO_USERS_WITH_FLUXERTAG_EXIST"),
            Self::NoVisionarySlotsAvailable => write!(f, "NO_VISIONARY_SLOTS_AVAILABLE"),
            Self::NotABotApplication => write!(f, "NOT_A_BOT_APPLICATION"),
            Self::NotFriendsWithUser => write!(f, "NOT_FRIENDS_WITH_USER"),
            Self::NotOwnerOfAdminApiKey => write!(f, "NOT_OWNER_OF_ADMIN_API_KEY"),
            Self::NsfwContentAgeRestricted => write!(f, "NSFW_CONTENT_AGE_RESTRICTED"),
            Self::PackAccessDenied => write!(f, "PACK_ACCESS_DENIED"),
            Self::PasskeyAuthenticationFailed => write!(f, "PASSKEY_AUTHENTICATION_FAILED"),
            Self::PasskeysDisabled => write!(f, "PASSKEYS_DISABLED"),
            Self::PhoneAlreadyUsed => write!(f, "PHONE_ALREADY_USED"),
            Self::PhoneRateLimitExceeded => write!(f, "PHONE_RATE_LIMIT_EXCEEDED"),
            Self::PhoneRequiredForSmsMfa => write!(f, "PHONE_REQUIRED_FOR_SMS_MFA"),
            Self::PhoneVerificationRequired => write!(f, "PHONE_VERIFICATION_REQUIRED"),
            Self::PremiumPurchaseBlocked => write!(f, "PREMIUM_PURCHASE_BLOCKED"),
            Self::PreviewMustBeJpeg => write!(f, "PREVIEW_MUST_BE_JPEG"),
            Self::ProcessingFailed => write!(f, "PROCESSING_FAILED"),
            Self::RateLimited => write!(f, "RATE_LIMITED"),
            Self::RedirectUriRequiredForNonBot => write!(f, "REDIRECT_URI_REQUIRED_FOR_NON_BOT"),
            Self::ReportAlreadyResolved => write!(f, "REPORT_ALREADY_RESOLVED"),
            Self::ReportBanned => write!(f, "REPORT_BANNED"),
            Self::ResponseValidationError => write!(f, "RESPONSE_VALIDATION_ERROR"),
            Self::ServiceUnavailable => write!(f, "SERVICE_UNAVAILABLE"),
            Self::SessionTokenMismatch => write!(f, "SESSION_TOKEN_MISMATCH"),
            Self::SlowmodeRateLimited => write!(f, "SLOWMODE_RATE_LIMITED"),
            Self::SmsMfaNotEnabled => write!(f, "SMS_MFA_NOT_ENABLED"),
            Self::SmsMfaRequiresTotp => write!(f, "SMS_MFA_REQUIRES_TOTP"),
            Self::SmsVerificationUnavailable => write!(f, "SMS_VERIFICATION_UNAVAILABLE"),
            Self::SsoRequired => write!(f, "SSO_REQUIRED"),
            Self::StreamKeyChannelMismatch => write!(f, "STREAM_KEY_CHANNEL_MISMATCH"),
            Self::StreamKeyScopeMismatch => write!(f, "STREAM_KEY_SCOPE_MISMATCH"),
            Self::StreamThumbnailPayloadEmpty => write!(f, "STREAM_THUMBNAIL_PAYLOAD_EMPTY"),
            Self::StripeError => write!(f, "STRIPE_ERROR"),
            Self::StripeGiftRedemptionInProgress => write!(f, "STRIPE_GIFT_REDEMPTION_IN_PROGRESS"),
            Self::StripeInvalidProduct => write!(f, "STRIPE_INVALID_PRODUCT"),
            Self::StripeInvalidProductConfiguration => {
                write!(f, "STRIPE_INVALID_PRODUCT_CONFIGURATION")
            }
            Self::StripeNoActiveSubscription => write!(f, "STRIPE_NO_ACTIVE_SUBSCRIPTION"),
            Self::StripeNoPurchaseHistory => write!(f, "STRIPE_NO_PURCHASE_HISTORY"),
            Self::StripeNoSubscription => write!(f, "STRIPE_NO_SUBSCRIPTION"),
            Self::StripePaymentNotAvailable => write!(f, "STRIPE_PAYMENT_NOT_AVAILABLE"),
            Self::StripeSubscriptionAlreadyCanceling => {
                write!(f, "STRIPE_SUBSCRIPTION_ALREADY_CANCELING")
            }
            Self::StripeSubscriptionNotCanceling => write!(f, "STRIPE_SUBSCRIPTION_NOT_CANCELING"),
            Self::StripeSubscriptionPeriodEndMissing => {
                write!(f, "STRIPE_SUBSCRIPTION_PERIOD_END_MISSING")
            }
            Self::StripeWebhookNotAvailable => write!(f, "STRIPE_WEBHOOK_NOT_AVAILABLE"),
            Self::StripeWebhookSignatureInvalid => write!(f, "STRIPE_WEBHOOK_SIGNATURE_INVALID"),
            Self::StripeWebhookSignatureMissing => write!(f, "STRIPE_WEBHOOK_SIGNATURE_MISSING"),
            Self::DonationAmountInvalid => write!(f, "DONATION_AMOUNT_INVALID"),
            Self::DonationMagicLinkExpired => write!(f, "DONATION_MAGIC_LINK_EXPIRED"),
            Self::DonationMagicLinkInvalid => write!(f, "DONATION_MAGIC_LINK_INVALID"),
            Self::DonationMagicLinkUsed => write!(f, "DONATION_MAGIC_LINK_USED"),
            Self::DonorNotFound => write!(f, "DONOR_NOT_FOUND"),
            Self::SudoModeRequired => write!(f, "SUDO_MODE_REQUIRED"),
            Self::TagAlreadyTaken => write!(f, "TAG_ALREADY_TAKEN"),
            Self::TemporaryInviteRequiresPresence => {
                write!(f, "TEMPORARY_INVITE_REQUIRES_PRESENCE")
            }
            Self::TestHarnessDisabled => write!(f, "TEST_HARNESS_DISABLED"),
            Self::TestHarnessForbidden => write!(f, "TEST_HARNESS_FORBIDDEN"),
            Self::TwoFaNotEnabled => write!(f, "TWO_FA_NOT_ENABLED"),
            Self::TwoFactorRequired => write!(f, "TWO_FACTOR_REQUIRED"),
            Self::Unauthorized => write!(f, "UNAUTHORIZED"),
            Self::UnclaimedAccountCannotAcceptFriendRequests => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_ACCEPT_FRIEND_REQUESTS")
            }
            Self::UnclaimedAccountCannotAddReactions => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_ADD_REACTIONS")
            }
            Self::UnclaimedAccountCannotCreateApplications => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_CREATE_APPLICATIONS")
            }
            Self::UnclaimedAccountCannotJoinGroupDms => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_JOIN_GROUP_DMS")
            }
            Self::UnclaimedAccountCannotJoinOneOnOneVoiceCalls => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_JOIN_ONE_ON_ONE_VOICE_CALLS")
            }
            Self::UnclaimedAccountCannotJoinVoiceChannels => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_JOIN_VOICE_CHANNELS")
            }
            Self::UnclaimedAccountCannotMakePurchases => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_MAKE_PURCHASES")
            }
            Self::UnclaimedAccountCannotSendDirectMessages => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_SEND_DIRECT_MESSAGES")
            }
            Self::UnclaimedAccountCannotSendFriendRequests => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_SEND_FRIEND_REQUESTS")
            }
            Self::UnclaimedAccountCannotSendMessages => {
                write!(f, "UNCLAIMED_ACCOUNT_CANNOT_SEND_MESSAGES")
            }
            Self::UnknownChannel => write!(f, "UNKNOWN_CHANNEL"),
            Self::UnknownEmoji => write!(f, "UNKNOWN_EMOJI"),
            Self::UnknownFavoriteMeme => write!(f, "UNKNOWN_FAVORITE_MEME"),
            Self::UnknownGiftCode => write!(f, "UNKNOWN_GIFT_CODE"),
            Self::UnknownGuild => write!(f, "UNKNOWN_GUILD"),
            Self::UnknownHarvest => write!(f, "UNKNOWN_HARVEST"),
            Self::UnknownInvite => write!(f, "UNKNOWN_INVITE"),
            Self::UnknownMember => write!(f, "UNKNOWN_MEMBER"),
            Self::UnknownMessage => write!(f, "UNKNOWN_MESSAGE"),
            Self::UnknownPack => write!(f, "UNKNOWN_PACK"),
            Self::UnknownReport => write!(f, "UNKNOWN_REPORT"),
            Self::UnknownRole => write!(f, "UNKNOWN_ROLE"),
            Self::UnknownSticker => write!(f, "UNKNOWN_STICKER"),
            Self::UnknownSuspiciousFlag => write!(f, "UNKNOWN_SUSPICIOUS_FLAG"),
            Self::UnknownUserFlag => write!(f, "UNKNOWN_USER_FLAG"),
            Self::UnknownUser => write!(f, "UNKNOWN_USER"),
            Self::UnknownVoiceRegion => write!(f, "UNKNOWN_VOICE_REGION"),
            Self::UnknownVoiceServer => write!(f, "UNKNOWN_VOICE_SERVER"),
            Self::UnknownWebauthnCredential => write!(f, "UNKNOWN_WEBAUTHN_CREDENTIAL"),
            Self::UnknownApplication => write!(f, "UNKNOWN_APPLICATION"),
            Self::UnknownWebhook => write!(f, "UNKNOWN_WEBHOOK"),
            Self::UnsupportedResponseType => write!(f, "UNSUPPORTED_RESPONSE_TYPE"),
            Self::UsernameNotAvailable => write!(f, "USERNAME_NOT_AVAILABLE"),
            Self::UpdateFailed => write!(f, "UPDATE_FAILED"),
            Self::UserBannedFromGuild => write!(f, "USER_BANNED_FROM_GUILD"),
            Self::UserIpBannedFromGuild => write!(f, "USER_IP_BANNED_FROM_GUILD"),
            Self::UserNotInVoice => write!(f, "USER_NOT_IN_VOICE"),
            Self::UserOwnsGuilds => write!(f, "USER_OWNS_GUILDS"),
            Self::ValidationError => write!(f, "VALIDATION_ERROR"),
            Self::VoiceChannelFull => write!(f, "VOICE_CHANNEL_FULL"),
            Self::WebauthnCredentialLimitReached => write!(f, "WEBAUTHN_CREDENTIAL_LIMIT_REACHED"),
        }
    }
}

