/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationResponse {
    /// The unique identifier of the application
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the application
    #[serde(rename = "name")]
    pub name: String,
    /// The registered redirect URIs for `OAuth2`
    #[serde(rename = "redirect_uris")]
    pub redirect_uris: Vec<String>,
    /// Whether the bot can be invited by anyone
    #[serde(rename = "bot_public")]
    pub bot_public: bool,
    /// Whether the bot requires `OAuth2` code grant
    #[serde(rename = "bot_require_code_grant")]
    pub bot_require_code_grant: bool,
    /// The client secret for `OAuth2` authentication
    #[serde(rename = "client_secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<Box<models::ApplicationBotResponse>>,
}

impl ApplicationResponse {
    #[must_use]
    pub fn new(
        id: String,
        name: String,
        redirect_uris: Vec<String>,
        bot_public: bool,
        bot_require_code_grant: bool,
    ) -> ApplicationResponse {
        ApplicationResponse {
            id,
            name,
            redirect_uris,
            bot_public,
            bot_require_code_grant,
            client_secret: None,
            bot: None,
        }
    }
}
