/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `AuditLogChangeSchemaNewValue` : Value after the change
/// Value after the change
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuditLogChangeSchemaNewValue {
    String(String),
    Number(f64),
    Boolean(bool),
    ArrayVecString(Vec<String>),
    ArrayVecf64(Vec<f64>),
    AuditLogChangeSchemaOldValueOneOf(Box<models::AuditLogChangeSchemaOldValueOneOf>),
}

impl Default for AuditLogChangeSchemaNewValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
