/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMfaRequiredResponse {
    /// Indicates MFA is required to complete authentication
    #[serde(rename = "mfa")]
    pub mfa: Mfa,
    /// MFA ticket to use when completing MFA verification
    #[serde(rename = "ticket")]
    pub ticket: String,
    /// List of allowed MFA methods
    #[serde(rename = "allowed_methods")]
    pub allowed_methods: Vec<String>,
    #[serde(
        rename = "sms_phone_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sms_phone_hint: Option<Option<String>>,
    /// Whether SMS MFA is available
    #[serde(rename = "sms")]
    pub sms: bool,
    /// Whether TOTP authenticator MFA is available
    #[serde(rename = "totp")]
    pub totp: bool,
    /// Whether `WebAuthn` security key MFA is available
    #[serde(rename = "webauthn")]
    pub webauthn: bool,
}

impl AuthMfaRequiredResponse {
    #[must_use] 
    pub fn new(
        mfa: Mfa,
        ticket: String,
        allowed_methods: Vec<String>,
        sms: bool,
        totp: bool,
        webauthn: bool,
    ) -> AuthMfaRequiredResponse {
        AuthMfaRequiredResponse {
            mfa,
            ticket,
            allowed_methods,
            sms_phone_hint: None,
            sms,
            totp,
            webauthn,
        }
    }
}
/// Indicates MFA is required to complete authentication
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Mfa {
    #[serde(rename = "true")]
    #[default]
    True,
}

