/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthLoginResponse {
    AuthTokenWithUserIdResponse(Box<models::AuthTokenWithUserIdResponse>),
    AuthMfaRequiredResponse(Box<models::AuthMfaRequiredResponse>),
}

impl Default for AuthLoginResponse {
    fn default() -> Self {
        Self::AuthTokenWithUserIdResponse(Default::default())
    }
}
/// Indicates MFA is required to complete authentication
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Mfa {
    #[serde(rename = "true")]
    #[default]
    True,
}

