/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BanGuildMemberRequest {
    /// Number of days of messages to delete from the banned user (0-7)
    #[serde(
        rename = "delete_message_days",
        skip_serializing_if = "Option::is_none"
    )]
    pub delete_message_days: Option<i32>,
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
    /// Duration of the ban in seconds (0 for permanent, or a valid temporary duration)
    #[serde(
        rename = "ban_duration_seconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub ban_duration_seconds: Option<i32>,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl BanGuildMemberRequest {
    #[must_use] 
    pub fn new(guild_id: String, user_id: String) -> BanGuildMemberRequest {
        BanGuildMemberRequest {
            delete_message_days: None,
            reason: None,
            ban_duration_seconds: None,
            guild_id,
            user_id,
        }
    }
}
