/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotTokenResetResponse {
    /// The new bot token
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "bot")]
    pub bot: Box<models::ApplicationBotResponse>,
}

impl BotTokenResetResponse {
    #[must_use]
    pub fn new(token: String, bot: models::ApplicationBotResponse) -> BotTokenResetResponse {
        BotTokenResetResponse {
            token,
            bot: Box::new(bot),
        }
    }
}
