/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkDeleteMessagesRequest {
    /// Array of message IDs to delete
    #[serde(rename = "message_ids")]
    pub message_ids: Vec<String>,
}

impl BulkDeleteMessagesRequest {
    #[must_use]
    pub fn new(message_ids: Vec<String>) -> BulkDeleteMessagesRequest {
        BulkDeleteMessagesRequest { message_ids }
    }
}
