/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkOperationResponse {
    #[serde(rename = "successful")]
    pub successful: Vec<String>,
    #[serde(rename = "failed")]
    pub failed: Vec<models::BulkOperationFailedResponse>,
}

impl BulkOperationResponse {
    #[must_use] 
    pub fn new(
        successful: Vec<String>,
        failed: Vec<models::BulkOperationFailedResponse>,
    ) -> BulkOperationResponse {
        BulkOperationResponse { successful, failed }
    }
}
