/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkScheduleUserDeletionRequest {
    /// List of user IDs to schedule deletion for
    #[serde(rename = "user_ids")]
    pub user_ids: Vec<String>,
    /// Code indicating the reason for deletion
    #[serde(rename = "reason_code")]
    pub reason_code: i32,
    /// Public-facing reason for the deletion
    #[serde(rename = "public_reason", skip_serializing_if = "Option::is_none")]
    pub public_reason: Option<String>,
    /// Number of days until the accounts are deleted
    #[serde(
        rename = "days_until_deletion",
        skip_serializing_if = "Option::is_none"
    )]
    pub days_until_deletion: Option<i32>,
}

impl BulkScheduleUserDeletionRequest {
    #[must_use] 
    pub fn new(user_ids: Vec<String>, reason_code: i32) -> BulkScheduleUserDeletionRequest {
        BulkScheduleUserDeletionRequest {
            user_ids,
            reason_code,
            public_reason: None,
            days_until_deletion: None,
        }
    }
}
