/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpdateGuildFeaturesRequest {
    /// List of guild IDs to update
    #[serde(rename = "guild_ids")]
    pub guild_ids: Vec<String>,
    /// Guild features to add to all specified guilds
    #[serde(rename = "add_features", skip_serializing_if = "Option::is_none")]
    pub add_features: Option<Vec<String>>,
    /// Guild features to remove from all specified guilds
    #[serde(rename = "remove_features", skip_serializing_if = "Option::is_none")]
    pub remove_features: Option<Vec<String>>,
}

impl BulkUpdateGuildFeaturesRequest {
    #[must_use]
    pub fn new(guild_ids: Vec<String>) -> BulkUpdateGuildFeaturesRequest {
        BulkUpdateGuildFeaturesRequest {
            guild_ids,
            add_features: None,
            remove_features: None,
        }
    }
}
