/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChannelUpdateRequest {
    ChannelUpdateTextRequest(Box<models::ChannelUpdateTextRequest>),
    ChannelUpdateVoiceRequest(Box<models::ChannelUpdateVoiceRequest>),
    ChannelUpdateCategoryRequest(Box<models::ChannelUpdateCategoryRequest>),
    ChannelUpdateLinkRequest(Box<models::ChannelUpdateLinkRequest>),
    ChannelUpdateGroupDmRequest(Box<models::ChannelUpdateGroupDmRequest>),
}

impl Default for ChannelUpdateRequest {
    fn default() -> Self {
        Self::ChannelUpdateTextRequest(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Type {
    #[serde(rename = "0")]
    #[default]
    Variant0,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "998")]
    Variant998,
    #[serde(rename = "3")]
    Variant3,
}

