/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelResponse {
    /// The unique identifier (snowflake) for this channel
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
    /// The name of the channel
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "topic",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub topic: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    #[serde(
        rename = "icon",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub icon: Option<Option<String>>,
    #[serde(
        rename = "owner_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<String>>,
    /// The type of the channel
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(
        rename = "parent_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_id: Option<Option<String>>,
    #[serde(
        rename = "bitrate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bitrate: Option<Option<i32>>,
    #[serde(
        rename = "user_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_limit: Option<Option<i32>>,
    #[serde(
        rename = "rtc_region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rtc_region: Option<Option<String>>,
    #[serde(
        rename = "last_message_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_message_id: Option<Option<String>>,
    #[serde(
        rename = "last_pin_timestamp",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_pin_timestamp: Option<Option<String>>,
    /// The permission overwrites for this channel
    #[serde(
        rename = "permission_overwrites",
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_overwrites: Option<Vec<models::ChannelOverwriteResponse>>,
    /// The recipients of the DM channel
    #[serde(rename = "recipients", skip_serializing_if = "Option::is_none")]
    pub recipients: Option<Vec<models::UserPartialResponse>>,
    /// Whether the channel is marked as NSFW
    #[serde(rename = "nsfw", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<bool>,
    #[serde(
        rename = "rate_limit_per_user",
        skip_serializing_if = "Option::is_none"
    )]
    pub rate_limit_per_user: Option<i32>,
    /// Custom nicknames for users in this channel (for group DMs)
    #[serde(rename = "nicks", skip_serializing_if = "Option::is_none")]
    pub nicks: Option<std::collections::HashMap<String, String>>,
}

impl ChannelResponse {
    #[must_use] 
    pub fn new(id: String, r#type: i32) -> ChannelResponse {
        ChannelResponse {
            id,
            guild_id: None,
            name: None,
            topic: None,
            url: None,
            icon: None,
            owner_id: None,
            r#type,
            position: None,
            parent_id: None,
            bitrate: None,
            user_limit: None,
            rtc_region: None,
            last_message_id: None,
            last_pin_timestamp: None,
            permission_overwrites: None,
            recipients: None,
            nsfw: None,
            rate_limit_per_user: None,
            nicks: None,
        }
    }
}
