/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `ChannelNicknameOverridesValue` : Nickname or null to clear
/// Nickname or null to clear
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChannelNicknameOverridesValue {
    String(String),
}

impl Default for ChannelNicknameOverridesValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
