/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelOverwriteResponse {
    /// The unique identifier for the role or user this overwrite applies to
    #[serde(rename = "id")]
    pub id: String,
    /// The type of entity the overwrite applies to
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The bitwise value of allowed permissions
    #[serde(rename = "allow")]
    pub allow: String,
    /// The bitwise value of denied permissions
    #[serde(rename = "deny")]
    pub deny: String,
}

impl ChannelOverwriteResponse {
    #[must_use] 
    pub fn new(id: String, r#type: Type, allow: String, deny: String) -> ChannelOverwriteResponse {
        ChannelOverwriteResponse {
            id,
            r#type,
            allow,
            deny,
        }
    }
}
/// The type of entity the overwrite applies to
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Type {
    #[serde(rename = "0")]
    #[default]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

