/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelUpdateVoiceRequest {
    #[serde(
        rename = "topic",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub topic: Option<Option<String>>,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    #[serde(
        rename = "parent_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parent_id: Option<Option<String>>,
    #[serde(
        rename = "bitrate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bitrate: Option<Option<i32>>,
    #[serde(
        rename = "user_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_limit: Option<Option<i32>>,
    /// Permission overwrites for roles and members
    #[serde(
        rename = "permission_overwrites",
        skip_serializing_if = "Option::is_none"
    )]
    pub permission_overwrites: Option<Vec<models::ChannelOverwriteRequest>>,
    #[serde(
        rename = "nsfw",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nsfw: Option<Option<bool>>,
    #[serde(
        rename = "rate_limit_per_user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rate_limit_per_user: Option<Option<i32>>,
    /// Base64-encoded image data
    #[serde_as(as = "super::DoubleOption<serde_with::base64::Base64>")]
    #[serde(rename = "icon", default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<Vec<u8>>>,
    #[serde(
        rename = "owner_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub owner_id: Option<Option<String>>,
    /// User nickname overrides (user ID to nickname mapping)
    #[serde(rename = "nicks", skip_serializing_if = "Option::is_none")]
    pub nicks: Option<std::collections::HashMap<String, models::ChannelNicknameOverridesValue>>,
    #[serde(
        rename = "rtc_region",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rtc_region: Option<Option<String>>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl ChannelUpdateVoiceRequest {
    #[must_use]
    pub fn new(r#type: Type) -> ChannelUpdateVoiceRequest {
        ChannelUpdateVoiceRequest {
            topic: None,
            url: None,
            parent_id: None,
            bitrate: None,
            user_limit: None,
            permission_overwrites: None,
            nsfw: None,
            rate_limit_per_user: None,
            icon: None,
            owner_id: None,
            nicks: None,
            rtc_region: None,
            r#type,
            name: None,
        }
    }
}
///
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "2")]
    #[default]
    Variant2,
}
