/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteChunkedUploadResponse {
    /// The temporary filename used to reference this upload
    #[serde(rename = "upload_filename")]
    pub upload_filename: String,
    /// The total size of the uploaded file in bytes
    #[serde(rename = "file_size")]
    pub file_size: i32,
    /// The MIME type of the uploaded file
    #[serde(rename = "content_type")]
    pub content_type: String,
}

impl CompleteChunkedUploadResponse {
    #[must_use]
    pub fn new(
        upload_filename: String,
        file_size: i32,
        content_type: String,
    ) -> CompleteChunkedUploadResponse {
        CompleteChunkedUploadResponse {
            upload_filename,
            file_size,
            content_type,
        }
    }
}
