/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteChunkedUploadRequestEtagsInner {
    /// The zero-based index of the chunk
    #[serde(rename = "chunk_index")]
    pub chunk_index: i64,
    /// The `ETag` returned when the chunk was uploaded
    #[serde(rename = "etag")]
    pub etag: String,
}

impl CompleteChunkedUploadRequestEtagsInner {
    #[must_use]
    pub fn new(chunk_index: i64, etag: String) -> CompleteChunkedUploadRequestEtagsInner {
        CompleteChunkedUploadRequestEtagsInner { chunk_index, etag }
    }
}
