/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionVerificationResponse {
    /// The verification token to place in DNS or profile
    #[serde(rename = "token")]
    pub token: String,
    /// The type of connection being verified
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The connection identifier (handle or domain)
    #[serde(rename = "id")]
    pub id: String,
    /// Human-readable instructions for completing verification
    #[serde(rename = "instructions")]
    pub instructions: String,
    /// Signed token the client sends back at verify time
    #[serde(rename = "initiation_token")]
    pub initiation_token: String,
}

impl ConnectionVerificationResponse {
    #[must_use] 
    pub fn new(
        token: String,
        r#type: Type,
        id: String,
        instructions: String,
        initiation_token: String,
    ) -> ConnectionVerificationResponse {
        ConnectionVerificationResponse {
            token,
            r#type,
            id,
            instructions,
            initiation_token,
        }
    }
}
/// The type of connection being verified
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Type {
    #[serde(rename = "bsky")]
    #[default]
    Bsky,
    #[serde(rename = "domain")]
    Domain,
}

