/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFavoriteMemeFromUrlBodySchema {
    #[serde(
        rename = "alt_text",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub alt_text: Option<Option<String>>,
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<Vec<String>>>,
    /// URL of the image or video to save as a favorite meme
    #[serde(rename = "url")]
    pub url: String,
    #[serde(
        rename = "klipy_slug",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub klipy_slug: Option<Option<String>>,
    #[serde(
        rename = "tenor_slug_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tenor_slug_id: Option<Option<String>>,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
}

impl CreateFavoriteMemeFromUrlBodySchema {
    #[must_use]
    pub fn new(url: String) -> CreateFavoriteMemeFromUrlBodySchema {
        CreateFavoriteMemeFromUrlBodySchema {
            alt_text: None,
            tags: None,
            url,
            klipy_slug: None,
            tenor_slug_id: None,
            name: None,
        }
    }
}
