/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAdminApiKeyResponse {
    /// Unique identifier for the API key
    #[serde(rename = "key_id")]
    pub key_id: String,
    /// The generated API key secret (only shown once)
    #[serde(rename = "key")]
    pub key: String,
    /// Display name for the API key
    #[serde(rename = "name")]
    pub name: String,
    /// ISO 8601 timestamp when the key was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "expires_at", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    /// List of access control permissions for the key
    #[serde(rename = "acls")]
    pub acls: Vec<String>,
}

impl CreateAdminApiKeyResponse {
    #[must_use]
    pub fn new(
        key_id: String,
        key: String,
        name: String,
        created_at: String,
        expires_at: Option<String>,
        acls: Vec<String>,
    ) -> CreateAdminApiKeyResponse {
        CreateAdminApiKeyResponse {
            key_id,
            key,
            name,
            created_at,
            expires_at,
            acls,
        }
    }
}
