/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateChunkedUploadRequest {
    /// The name of the file being uploaded
    #[serde(rename = "filename")]
    pub filename: String,
    /// The total size of the file in bytes
    #[serde(rename = "file_size")]
    pub file_size: i64,
}

impl CreateChunkedUploadRequest {
    #[must_use]
    pub fn new(filename: String, file_size: i64) -> CreateChunkedUploadRequest {
        CreateChunkedUploadRequest {
            filename,
            file_size,
        }
    }
}
