/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePrivateChannelRequest {
    #[serde(rename = "recipient_id", skip_serializing_if = "Option::is_none")]
    pub recipient_id: Option<String>,
    /// Array of user IDs for creating a group DM (max 9)
    #[serde(rename = "recipients", skip_serializing_if = "Option::is_none")]
    pub recipients: Option<Vec<String>>,
}

impl CreatePrivateChannelRequest {
    #[must_use] 
    pub fn new() -> CreatePrivateChannelRequest {
        CreatePrivateChannelRequest {
            recipient_id: None,
            recipients: None,
        }
    }
}
