/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateConnectionRequest {
    /// The type of connection to create
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The connection identifier (handle or domain)
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "visibility_flags", skip_serializing_if = "Option::is_none")]
    pub visibility_flags: Option<i32>,
}

impl CreateConnectionRequest {
    #[must_use]
    pub fn new(r#type: Type, identifier: String) -> CreateConnectionRequest {
        CreateConnectionRequest {
            r#type,
            identifier,
            visibility_flags: None,
        }
    }
}
/// The type of connection to create
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "bsky")]
    #[default]
    Bsky,
    #[serde(rename = "domain")]
    Domain,
}
