/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomStatusResponse {
    #[serde(
        rename = "text",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub text: Option<Option<String>>,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
    #[serde(
        rename = "emoji_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub emoji_id: Option<Option<String>>,
    #[serde(
        rename = "emoji_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub emoji_name: Option<Option<String>>,
    /// Whether the status emoji is animated
    #[serde(rename = "emoji_animated")]
    pub emoji_animated: bool,
}

impl CustomStatusResponse {
    #[must_use] 
    pub fn new(emoji_animated: bool) -> CustomStatusResponse {
        CustomStatusResponse {
            text: None,
            expires_at: None,
            emoji_id: None,
            emoji_name: None,
            emoji_animated,
        }
    }
}
