/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteVoiceServerRequest {
    /// ID of the region the server belongs to
    #[serde(rename = "region_id")]
    pub region_id: String,
    /// ID of the voice server to delete
    #[serde(rename = "server_id")]
    pub server_id: String,
}

impl DeleteVoiceServerRequest {
    #[must_use] 
    pub fn new(region_id: String, server_id: String) -> DeleteVoiceServerRequest {
        DeleteVoiceServerRequest {
            region_id,
            server_id,
        }
    }
}
