/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryGuildResponse {
    /// Guild ID
    #[serde(rename = "id")]
    pub id: String,
    /// Guild name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "icon",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub icon: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Discovery category type
    #[serde(rename = "category_type")]
    pub category_type: f64,
    /// Approximate member count
    #[serde(rename = "member_count")]
    pub member_count: f64,
    /// Approximate online member count
    #[serde(rename = "online_count")]
    pub online_count: f64,
    /// Guild feature flags
    #[serde(rename = "features")]
    pub features: Vec<String>,
    /// Verification level
    #[serde(rename = "verification_level")]
    pub verification_level: f64,
}

impl DiscoveryGuildResponse {
    #[must_use] 
    pub fn new(
        id: String,
        name: String,
        category_type: f64,
        member_count: f64,
        online_count: f64,
        features: Vec<String>,
        verification_level: f64,
    ) -> DiscoveryGuildResponse {
        DiscoveryGuildResponse {
            id,
            name,
            icon: None,
            description: None,
            category_type,
            member_count,
            online_count,
            features,
            verification_level,
        }
    }
}
