/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryApplicationRequest {
    /// Description for discovery listing
    #[serde(rename = "description")]
    pub description: String,
    /// Discovery category type
    #[serde(rename = "category_type")]
    pub category_type: i32,
}

impl DiscoveryApplicationRequest {
    #[must_use] 
    pub fn new(description: String, category_type: i32) -> DiscoveryApplicationRequest {
        DiscoveryApplicationRequest {
            description,
            category_type,
        }
    }
}
