/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscoveryGuildListResponse {
    /// Discovery guild results
    #[serde(rename = "guilds")]
    pub guilds: Vec<models::DiscoveryGuildResponse>,
    /// Total number of matching guilds
    #[serde(rename = "total")]
    pub total: f64,
}

impl DiscoveryGuildListResponse {
    #[must_use]
    pub fn new(
        guilds: Vec<models::DiscoveryGuildResponse>,
        total: f64,
    ) -> DiscoveryGuildListResponse {
        DiscoveryGuildListResponse { guilds, total }
    }
}
