/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailChangeRequestNewResponse {
    /// Ticket associated with the email change attempt
    #[serde(rename = "ticket")]
    pub ticket: String,
    /// The new email address the user wants to verify
    #[serde(rename = "new_email")]
    pub new_email: String,
    /// ISO8601 timestamp when the new email code expires
    #[serde(rename = "new_code_expires_at")]
    pub new_code_expires_at: String,
    #[serde(
        rename = "resend_available_at",
        deserialize_with = "Option::deserialize"
    )]
    pub resend_available_at: Option<String>,
}

impl EmailChangeRequestNewResponse {
    #[must_use]
    pub fn new(
        ticket: String,
        new_email: String,
        new_code_expires_at: String,
        resend_available_at: Option<String>,
    ) -> EmailChangeRequestNewResponse {
        EmailChangeRequestNewResponse {
            ticket,
            new_email,
            new_code_expires_at,
            resend_available_at,
        }
    }
}
