/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbedFooterResponse {
    /// The footer text
    #[serde(rename = "text")]
    pub text: String,
    #[serde(
        rename = "icon_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub icon_url: Option<Option<String>>,
    #[serde(
        rename = "proxy_icon_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub proxy_icon_url: Option<Option<String>>,
}

impl EmbedFooterResponse {
    #[must_use]
    pub fn new(text: String) -> EmbedFooterResponse {
        EmbedFooterResponse {
            text,
            icon_url: None,
            proxy_icon_url: None,
        }
    }
}
