/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbedMediaResponse {
    /// The URL of the media
    #[serde(rename = "url")]
    pub url: String,
    #[serde(
        rename = "proxy_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub proxy_url: Option<Option<String>>,
    #[serde(
        rename = "content_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_type: Option<Option<String>>,
    #[serde(
        rename = "content_hash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_hash: Option<Option<String>>,
    #[serde(
        rename = "width",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub width: Option<Option<i32>>,
    #[serde(
        rename = "height",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub height: Option<Option<i32>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "placeholder",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub placeholder: Option<Option<String>>,
    #[serde(
        rename = "duration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub duration: Option<Option<i32>>,
    /// The bitwise flags for this media
    #[serde(rename = "flags")]
    pub flags: i32,
}

impl EmbedMediaResponse {
    #[must_use]
    pub fn new(url: String, flags: i32) -> EmbedMediaResponse {
        EmbedMediaResponse {
            url,
            proxy_url: None,
            content_type: None,
            content_hash: None,
            width: None,
            height: None,
            description: None,
            placeholder: None,
            duration: None,
            flags,
        }
    }
}
