/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayBotResponse {
    /// WebSocket URL to connect to the gateway
    #[serde(rename = "url")]
    pub url: String,
    /// Recommended number of shards to use when connecting
    #[serde(rename = "shards")]
    pub shards: i32,
    #[serde(rename = "session_start_limit")]
    pub session_start_limit: Box<models::GatewayBotResponseSessionStartLimit>,
}

impl GatewayBotResponse {
    #[must_use]
    pub fn new(
        url: String,
        shards: i32,
        session_start_limit: models::GatewayBotResponseSessionStartLimit,
    ) -> GatewayBotResponse {
        GatewayBotResponse {
            url,
            shards,
            session_start_limit: Box::new(session_start_limit),
        }
    }
}
