/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetVoiceServerResponse {
    #[serde(rename = "server", deserialize_with = "Option::deserialize")]
    pub server: Option<Box<models::VoiceServerAdminResponse>>,
}

impl GetVoiceServerResponse {
    #[must_use] 
    pub fn new(server: Option<models::VoiceServerAdminResponse>) -> GetVoiceServerResponse {
        GetVoiceServerResponse {
            server: server.map(Box::new),
        }
    }
}
