/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiftCodeMetadataResponse {
    /// The unique gift code string
    #[serde(rename = "code")]
    pub code: String,
    /// Duration of the subscription gift in months
    #[serde(rename = "duration_months")]
    pub duration_months: i32,
    /// Timestamp when the gift code was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "created_by")]
    pub created_by: Box<models::UserPartialResponse>,
    #[serde(
        rename = "redeemed_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redeemed_at: Option<Option<String>>,
    #[serde(
        rename = "redeemed_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redeemed_by: Option<Option<Box<models::UserPartialResponse>>>,
}

impl GiftCodeMetadataResponse {
    #[must_use] 
    pub fn new(
        code: String,
        duration_months: i32,
        created_at: String,
        created_by: models::UserPartialResponse,
    ) -> GiftCodeMetadataResponse {
        GiftCodeMetadataResponse {
            code,
            duration_months,
            created_at,
            created_by: Box::new(created_by),
            redeemed_at: None,
            redeemed_by: None,
        }
    }
}
