/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubWebhook {
    #[serde(
        rename = "action",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub action: Option<Option<String>>,
    #[serde(
        rename = "answer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub answer: Option<Option<Box<models::GitHubWebhookAnswer>>>,
    #[serde(
        rename = "check_run",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_run: Option<Option<Box<models::GitHubWebhookCheckRun>>>,
    #[serde(
        rename = "check_suite",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_suite: Option<Option<Box<models::GitHubWebhookCheckSuite>>>,
    #[serde(
        rename = "comment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub comment: Option<Option<Box<models::GitHubWebhookAnswer>>>,
    #[serde(
        rename = "commits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub commits: Option<Option<Vec<models::GitHubWebhookCommitsInner>>>,
    #[serde(
        rename = "compare",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub compare: Option<Option<String>>,
    #[serde(
        rename = "discussion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discussion: Option<Option<Box<models::GitHubWebhookDiscussion>>>,
    #[serde(
        rename = "forced",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub forced: Option<Option<bool>>,
    #[serde(
        rename = "forkee",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub forkee: Option<Option<Box<models::GitHubWebhookForkee>>>,
    #[serde(
        rename = "head_commit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub head_commit: Option<Option<Box<models::GitHubWebhookHeadCommit>>>,
    #[serde(
        rename = "issue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issue: Option<Option<Box<models::GitHubWebhookIssue>>>,
    #[serde(
        rename = "member",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub member: Option<Option<Box<models::GitHubWebhookMember>>>,
    #[serde(
        rename = "pull_request",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pull_request: Option<Option<Box<models::GitHubWebhookIssue>>>,
    #[serde(
        rename = "ref_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ref_type: Option<Option<String>>,
    #[serde(
        rename = "ref",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub r#ref: Option<Option<String>>,
    #[serde(
        rename = "release",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub release: Option<Option<Box<models::GitHubWebhookRelease>>>,
    #[serde(
        rename = "repository",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub repository: Option<Option<Box<models::GitHubWebhookForkee>>>,
    #[serde(
        rename = "review",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub review: Option<Option<Box<models::GitHubWebhookReview>>>,
    #[serde(rename = "sender")]
    pub sender: Box<models::GitHubWebhookAnswerUser>,
}

impl GitHubWebhook {
    #[must_use] 
    pub fn new(sender: models::GitHubWebhookAnswerUser) -> GitHubWebhook {
        GitHubWebhook {
            action: None,
            answer: None,
            check_run: None,
            check_suite: None,
            comment: None,
            commits: None,
            compare: None,
            discussion: None,
            forced: None,
            forkee: None,
            head_commit: None,
            issue: None,
            member: None,
            pull_request: None,
            ref_type: None,
            r#ref: None,
            release: None,
            repository: None,
            review: None,
            sender: Box::new(sender),
        }
    }
}
