/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubWebhookReview {
    #[serde(rename = "user")]
    pub user: Box<models::GitHubWebhookAnswerUser>,
    #[serde(
        rename = "body",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub body: Option<Option<String>>,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl GitHubWebhookReview {
    #[must_use]
    pub fn new(
        user: models::GitHubWebhookAnswerUser,
        html_url: String,
        state: String,
    ) -> GitHubWebhookReview {
        GitHubWebhookReview {
            user: Box::new(user),
            body: None,
            html_url,
            state,
        }
    }
}
