/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubWebhookHeadCommit {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "author")]
    pub author: Box<models::GitHubWebhookCommitsInnerAuthor>,
}

impl GitHubWebhookHeadCommit {
    #[must_use]
    pub fn new(
        id: String,
        url: String,
        message: String,
        author: models::GitHubWebhookCommitsInnerAuthor,
    ) -> GitHubWebhookHeadCommit {
        GitHubWebhookHeadCommit {
            id,
            url,
            message,
            author: Box::new(author),
        }
    }
}
