/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubWebhookForkee {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
}

impl GitHubWebhookForkee {
    #[must_use]
    pub fn new(id: i32, html_url: String, name: String, full_name: String) -> GitHubWebhookForkee {
        GitHubWebhookForkee {
            id,
            html_url,
            name,
            full_name,
        }
    }
}
