/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitHubWebhookCheckRunCheckSuite {
    #[serde(
        rename = "conclusion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub conclusion: Option<Option<String>>,
    #[serde(
        rename = "head_branch",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub head_branch: Option<Option<String>>,
    #[serde(rename = "head_sha")]
    pub head_sha: String,
    #[serde(
        rename = "pull_requests",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pull_requests:
        Option<Option<Vec<models::GitHubWebhookCheckRunCheckSuitePullRequestsInner>>>,
    #[serde(rename = "app")]
    pub app: Box<models::GitHubWebhookCheckRunCheckSuiteApp>,
}

impl GitHubWebhookCheckRunCheckSuite {
    #[must_use] 
    pub fn new(
        head_sha: String,
        app: models::GitHubWebhookCheckRunCheckSuiteApp,
    ) -> GitHubWebhookCheckRunCheckSuite {
        GitHubWebhookCheckRunCheckSuite {
            conclusion: None,
            head_branch: None,
            head_sha,
            pull_requests: None,
            app: Box::new(app),
        }
    }
}
