/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalSearchMessagesRequest {
    /// Number of results per page (1-25)
    #[serde(rename = "hits_per_page", skip_serializing_if = "Option::is_none")]
    pub hits_per_page: Option<i32>,
    /// Page number for pagination
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(rename = "max_id", skip_serializing_if = "Option::is_none")]
    pub max_id: Option<String>,
    #[serde(rename = "min_id", skip_serializing_if = "Option::is_none")]
    pub min_id: Option<String>,
    /// Text content to search for
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Multiple content queries to search for
    #[serde(rename = "contents", skip_serializing_if = "Option::is_none")]
    pub contents: Option<Vec<String>>,
    /// Exact phrases that must appear contiguously in message content
    #[serde(rename = "exact_phrases", skip_serializing_if = "Option::is_none")]
    pub exact_phrases: Option<Vec<String>>,
    /// Channel IDs to search in
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<Vec<String>>,
    /// Channel IDs to exclude from search
    #[serde(rename = "exclude_channel_id", skip_serializing_if = "Option::is_none")]
    pub exclude_channel_id: Option<Vec<String>>,
    /// Author types to filter by
    #[serde(rename = "author_type", skip_serializing_if = "Option::is_none")]
    pub author_type: Option<Vec<models::MessageAuthorType>>,
    /// Author types to exclude
    #[serde(
        rename = "exclude_author_type",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclude_author_type: Option<Vec<models::MessageAuthorType>>,
    /// Author user IDs to filter by
    #[serde(rename = "author_id", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<Vec<String>>,
    /// Author user IDs to exclude
    #[serde(rename = "exclude_author_id", skip_serializing_if = "Option::is_none")]
    pub exclude_author_id: Option<Vec<String>>,
    /// User IDs that must be mentioned
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<String>>,
    /// User IDs that must not be mentioned
    #[serde(rename = "exclude_mentions", skip_serializing_if = "Option::is_none")]
    pub exclude_mentions: Option<Vec<String>>,
    /// Filter by whether message mentions everyone
    #[serde(rename = "mention_everyone", skip_serializing_if = "Option::is_none")]
    pub mention_everyone: Option<bool>,
    /// Filter by pinned status
    #[serde(rename = "pinned", skip_serializing_if = "Option::is_none")]
    pub pinned: Option<bool>,
    /// Content types the message must have
    #[serde(rename = "has", skip_serializing_if = "Option::is_none")]
    pub has: Option<Vec<models::MessageContentType>>,
    /// Content types the message must not have
    #[serde(rename = "exclude_has", skip_serializing_if = "Option::is_none")]
    pub exclude_has: Option<Vec<models::MessageContentType>>,
    /// Embed types to filter by
    #[serde(rename = "embed_type", skip_serializing_if = "Option::is_none")]
    pub embed_type: Option<Vec<models::MessageEmbedType>>,
    /// Embed types to exclude
    #[serde(rename = "exclude_embed_type", skip_serializing_if = "Option::is_none")]
    pub exclude_embed_type: Option<Vec<models::MessageEmbedType>>,
    /// Embed providers to filter by
    #[serde(rename = "embed_provider", skip_serializing_if = "Option::is_none")]
    pub embed_provider: Option<Vec<String>>,
    /// Embed providers to exclude
    #[serde(
        rename = "exclude_embed_provider",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclude_embed_provider: Option<Vec<String>>,
    /// Link hostnames to filter by
    #[serde(rename = "link_hostname", skip_serializing_if = "Option::is_none")]
    pub link_hostname: Option<Vec<String>>,
    /// Link hostnames to exclude
    #[serde(
        rename = "exclude_link_hostname",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclude_link_hostname: Option<Vec<String>>,
    /// Attachment filenames to filter by
    #[serde(
        rename = "attachment_filename",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachment_filename: Option<Vec<String>>,
    /// Attachment filenames to exclude
    #[serde(
        rename = "exclude_attachment_filename",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclude_attachment_filename: Option<Vec<String>>,
    /// File extensions to filter by
    #[serde(
        rename = "attachment_extension",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachment_extension: Option<Vec<String>>,
    /// File extensions to exclude
    #[serde(
        rename = "exclude_attachment_extension",
        skip_serializing_if = "Option::is_none"
    )]
    pub exclude_attachment_extension: Option<Vec<String>>,
    #[serde(rename = "sort_by", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<models::MessageSortField>,
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<models::MessageSortOrder>,
    /// Whether to include NSFW channel results
    #[serde(rename = "include_nsfw", skip_serializing_if = "Option::is_none")]
    pub include_nsfw: Option<bool>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<models::MessageSearchScope>,
    #[serde(rename = "context_channel_id", skip_serializing_if = "Option::is_none")]
    pub context_channel_id: Option<String>,
    #[serde(rename = "context_guild_id", skip_serializing_if = "Option::is_none")]
    pub context_guild_id: Option<String>,
    /// Specific channel IDs to search in
    #[serde(rename = "channel_ids", skip_serializing_if = "Option::is_none")]
    pub channel_ids: Option<Vec<String>>,
}

impl GlobalSearchMessagesRequest {
    #[must_use] 
    pub fn new() -> GlobalSearchMessagesRequest {
        GlobalSearchMessagesRequest {
            hits_per_page: None,
            page: None,
            max_id: None,
            min_id: None,
            content: None,
            contents: None,
            exact_phrases: None,
            channel_id: None,
            exclude_channel_id: None,
            author_type: None,
            exclude_author_type: None,
            author_id: None,
            exclude_author_id: None,
            mentions: None,
            exclude_mentions: None,
            mention_everyone: None,
            pinned: None,
            has: None,
            exclude_has: None,
            embed_type: None,
            exclude_embed_type: None,
            embed_provider: None,
            exclude_embed_provider: None,
            link_hostname: None,
            exclude_link_hostname: None,
            attachment_filename: None,
            exclude_attachment_filename: None,
            attachment_extension: None,
            exclude_attachment_extension: None,
            sort_by: None,
            sort_order: None,
            include_nsfw: None,
            scope: None,
            context_channel_id: None,
            context_guild_id: None,
            channel_ids: None,
        }
    }
}
