/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupDmInviteMetadataResponse {
    /// The unique invite code
    #[serde(rename = "code")]
    pub code: String,
    /// The type of invite (group DM)
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "channel")]
    pub channel: Box<models::ChannelPartialResponse>,
    #[serde(
        rename = "inviter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inviter: Option<Option<Box<models::UserPartialResponse>>>,
    /// The current member count of the group DM
    #[serde(rename = "member_count")]
    pub member_count: i32,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
    /// Whether the invite grants temporary membership
    #[serde(rename = "temporary")]
    pub temporary: bool,
    /// ISO8601 timestamp of when the invite was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The number of times this invite has been used
    #[serde(rename = "uses")]
    pub uses: i32,
    /// The maximum number of times this invite can be used
    #[serde(rename = "max_uses")]
    pub max_uses: i32,
}

impl GroupDmInviteMetadataResponse {
    #[must_use]
    pub fn new(
        code: String,
        r#type: Type,
        channel: models::ChannelPartialResponse,
        member_count: i32,
        temporary: bool,
        created_at: String,
        uses: i32,
        max_uses: i32,
    ) -> GroupDmInviteMetadataResponse {
        GroupDmInviteMetadataResponse {
            code,
            r#type,
            channel: Box::new(channel),
            inviter: None,
            member_count,
            expires_at: None,
            temporary,
            created_at,
            uses,
            max_uses,
        }
    }
}
/// The type of invite (group DM)
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "1")]
    #[default]
    Variant1,
}
