/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildInviteResponse {
    /// The unique invite code
    #[serde(rename = "code")]
    pub code: String,
    /// The type of invite (guild)
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "guild")]
    pub guild: Box<models::GuildInviteMetadataResponseGuild>,
    #[serde(rename = "channel")]
    pub channel: Box<models::ChannelPartialResponse>,
    #[serde(
        rename = "inviter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inviter: Option<Option<Box<models::UserPartialResponse>>>,
    /// The approximate total member count of the guild
    #[serde(rename = "member_count")]
    pub member_count: i32,
    /// The approximate online member count of the guild
    #[serde(rename = "presence_count")]
    pub presence_count: i32,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
    /// Whether the invite grants temporary membership
    #[serde(rename = "temporary")]
    pub temporary: bool,
}

impl GuildInviteResponse {
    #[must_use]
    pub fn new(
        code: String,
        r#type: Type,
        guild: models::GuildInviteMetadataResponseGuild,
        channel: models::ChannelPartialResponse,
        member_count: i32,
        presence_count: i32,
        temporary: bool,
    ) -> GuildInviteResponse {
        GuildInviteResponse {
            code,
            r#type,
            guild: Box::new(guild),
            channel: Box::new(channel),
            inviter: None,
            member_count,
            presence_count,
            expires_at: None,
            temporary,
        }
    }
}
/// The type of invite (guild)
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "0")]
    #[default]
    Variant0,
}
