/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRoleUpdateRequest {
    /// The name of the role (1-100 characters)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The color of the role as an integer
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// Whether the role should be displayed separately in the member list
    #[serde(rename = "hoist", skip_serializing_if = "Option::is_none")]
    pub hoist: Option<bool>,
    #[serde(
        rename = "hoist_position",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hoist_position: Option<Option<i32>>,
    /// Whether the role can be mentioned by anyone
    #[serde(rename = "mentionable", skip_serializing_if = "Option::is_none")]
    pub mentionable: Option<bool>,
}

impl GuildRoleUpdateRequest {
    #[must_use]
    pub fn new() -> GuildRoleUpdateRequest {
        GuildRoleUpdateRequest {
            name: None,
            color: None,
            permissions: None,
            hoist: None,
            hoist_position: None,
            mentionable: None,
        }
    }
}
