/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildEmojiBulkCreateResponseFailedInner {
    /// The name of the emoji that failed to create
    #[serde(rename = "name")]
    pub name: String,
    /// The error message explaining why the emoji failed to create
    #[serde(rename = "error")]
    pub error: String,
}

impl GuildEmojiBulkCreateResponseFailedInner {
    #[must_use]
    pub fn new(name: String, error: String) -> GuildEmojiBulkCreateResponseFailedInner {
        GuildEmojiBulkCreateResponseFailedInner { name, error }
    }
}
