/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildVanityUrlResponse {
    #[serde(
        rename = "code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub code: Option<Option<String>>,
    /// The number of times this vanity URL has been used
    #[serde(rename = "uses")]
    pub uses: i32,
}

impl GuildVanityUrlResponse {
    #[must_use] 
    pub fn new(uses: i32) -> GuildVanityUrlResponse {
        GuildVanityUrlResponse { code: None, uses }
    }
}
