/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildEmojiWithUserResponse {
    /// The unique identifier for this emoji
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the emoji
    #[serde(rename = "name")]
    pub name: String,
    /// Whether this emoji is animated
    #[serde(rename = "animated")]
    pub animated: bool,
    #[serde(rename = "user")]
    pub user: Box<models::UserPartialResponse>,
}

impl GuildEmojiWithUserResponse {
    #[must_use]
    pub fn new(
        id: String,
        name: String,
        animated: bool,
        user: models::UserPartialResponse,
    ) -> GuildEmojiWithUserResponse {
        GuildEmojiWithUserResponse {
            id,
            name,
            animated,
            user: Box::new(user),
        }
    }
}
