/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildStickerUpdateRequest {
    /// The name of the sticker (2-30 characters)
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Array of autocomplete/suggestion tags (max 10 tags, each 1-30 characters)
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl GuildStickerUpdateRequest {
    #[must_use] 
    pub fn new(name: String) -> GuildStickerUpdateRequest {
        GuildStickerUpdateRequest {
            name,
            description: None,
            tags: None,
        }
    }
}
