/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildMemberSearchRequest {
    /// Text to search for in usernames, global names, and nicknames
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Maximum number of results to return
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Number of results to skip for pagination
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Filter by role IDs (member must have all specified roles)
    #[serde(rename = "role_ids", skip_serializing_if = "Option::is_none")]
    pub role_ids: Option<Vec<String>>,
    /// Filter members who joined at or after this unix timestamp
    #[serde(rename = "joined_at_gte", skip_serializing_if = "Option::is_none")]
    pub joined_at_gte: Option<i32>,
    /// Filter members who joined at or before this unix timestamp
    #[serde(rename = "joined_at_lte", skip_serializing_if = "Option::is_none")]
    pub joined_at_lte: Option<i32>,
    /// Filter by join source types
    #[serde(rename = "join_source_type", skip_serializing_if = "Option::is_none")]
    pub join_source_type: Option<Vec<i32>>,
    /// Filter by invite codes used to join
    #[serde(rename = "source_invite_code", skip_serializing_if = "Option::is_none")]
    pub source_invite_code: Option<Vec<String>>,
    /// Filter by bot status
    #[serde(rename = "is_bot", skip_serializing_if = "Option::is_none")]
    pub is_bot: Option<bool>,
    /// Filter members whose account was created at or after this unix timestamp
    #[serde(
        rename = "user_created_at_gte",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_created_at_gte: Option<i32>,
    /// Filter members whose account was created at or before this unix timestamp
    #[serde(
        rename = "user_created_at_lte",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_created_at_lte: Option<i32>,
    /// Sort results by field
    #[serde(rename = "sort_by", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<SortBy>,
    /// Sort order
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<SortOrder>,
}

impl GuildMemberSearchRequest {
    #[must_use] 
    pub fn new() -> GuildMemberSearchRequest {
        GuildMemberSearchRequest {
            query: None,
            limit: None,
            offset: None,
            role_ids: None,
            joined_at_gte: None,
            joined_at_lte: None,
            join_source_type: None,
            source_invite_code: None,
            is_bot: None,
            user_created_at_gte: None,
            user_created_at_lte: None,
            sort_by: None,
            sort_order: None,
        }
    }
}
/// Sort results by field
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum SortBy {
    #[serde(rename = "joinedAt")]
    #[default]
    JoinedAt,
    #[serde(rename = "relevance")]
    Relevance,
}

/// Sort order
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum SortOrder {
    #[serde(rename = "asc")]
    #[default]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

