/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildDeleteRequest {
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// MFA method to use for verification
    #[serde(rename = "mfa_method", skip_serializing_if = "Option::is_none")]
    pub mfa_method: Option<MfaMethod>,
    /// MFA verification code from authenticator app or SMS
    #[serde(rename = "mfa_code", skip_serializing_if = "Option::is_none")]
    pub mfa_code: Option<String>,
    /// `WebAuthn` authentication response
    #[serde(rename = "webauthn_response", skip_serializing_if = "Option::is_none")]
    pub webauthn_response: Option<serde_json::Value>,
    /// `WebAuthn` challenge string
    #[serde(rename = "webauthn_challenge", skip_serializing_if = "Option::is_none")]
    pub webauthn_challenge: Option<String>,
}

impl GuildDeleteRequest {
    #[must_use]
    pub fn new() -> GuildDeleteRequest {
        GuildDeleteRequest {
            password: None,
            mfa_method: None,
            mfa_code: None,
            webauthn_response: None,
            webauthn_challenge: None,
        }
    }
}
/// MFA method to use for verification
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum MfaMethod {
    #[serde(rename = "totp")]
    #[default]
    Totp,
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "webauthn")]
    Webauthn,
}
