/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRoleCreateRequest {
    /// The name of the role (1-100 characters)
    #[serde(rename = "name")]
    pub name: String,
    /// The color of the role as an integer (default: 0)
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
}

impl GuildRoleCreateRequest {
    #[must_use]
    pub fn new(name: String) -> GuildRoleCreateRequest {
        GuildRoleCreateRequest {
            name,
            color: None,
            permissions: None,
        }
    }
}
