/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildMemberSearchResponse {
    /// Guild ID
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    /// Matching members
    #[serde(rename = "members")]
    pub members: Vec<models::GuildMemberSearchResult>,
    /// Number of results in this page
    #[serde(rename = "page_result_count")]
    pub page_result_count: i32,
    /// Total number of matching results
    #[serde(rename = "total_result_count")]
    pub total_result_count: i32,
    /// Whether the guild members are currently being indexed
    #[serde(rename = "indexing")]
    pub indexing: bool,
}

impl GuildMemberSearchResponse {
    #[must_use] 
    pub fn new(
        guild_id: String,
        members: Vec<models::GuildMemberSearchResult>,
        page_result_count: i32,
        total_result_count: i32,
        indexing: bool,
    ) -> GuildMemberSearchResponse {
        GuildMemberSearchResponse {
            guild_id,
            members,
            page_result_count,
            total_result_count,
            indexing,
        }
    }
}
