/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildUpdateResponseGuild {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "features")]
    pub features: Vec<String>,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "icon", deserialize_with = "Option::deserialize")]
    pub icon: Option<String>,
    #[serde(rename = "banner", deserialize_with = "Option::deserialize")]
    pub banner: Option<String>,
    #[serde(rename = "member_count")]
    pub member_count: i32,
}

impl GuildUpdateResponseGuild {
    #[must_use]
    pub fn new(
        id: String,
        name: String,
        features: Vec<String>,
        owner_id: String,
        icon: Option<String>,
        banner: Option<String>,
        member_count: i32,
    ) -> GuildUpdateResponseGuild {
        GuildUpdateResponseGuild {
            id,
            name,
            features,
            owner_id,
            icon,
            banner,
            member_count,
        }
    }
}
