/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HarvestCreationResponseSchema {
    /// Unique identifier for the harvest request
    #[serde(rename = "harvest_id")]
    pub harvest_id: String,
    #[serde(rename = "status")]
    pub status: models::HarvestStatusEnum,
    /// ISO 8601 timestamp when the harvest request was created
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl HarvestCreationResponseSchema {
    #[must_use]
    pub fn new(
        harvest_id: String,
        status: models::HarvestStatusEnum,
        created_at: String,
    ) -> HarvestCreationResponseSchema {
        HarvestCreationResponseSchema {
            harvest_id,
            status,
            created_at,
        }
    }
}
