/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HarvestStatusResponseSchemaNullable {
    /// Unique identifier for the harvest request
    #[serde(rename = "harvest_id")]
    pub harvest_id: String,
    #[serde(rename = "status")]
    pub status: models::HarvestStatusEnum,
    /// ISO 8601 timestamp when the harvest request was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "started_at")]
    pub started_at: String,
    #[serde(rename = "completed_at")]
    pub completed_at: String,
    #[serde(rename = "failed_at")]
    pub failed_at: String,
    #[serde(rename = "file_size")]
    pub file_size: String,
    /// Harvest progress as a percentage value between 0 and 100
    #[serde(rename = "progress_percent")]
    pub progress_percent: f64,
    #[serde(rename = "progress_step")]
    pub progress_step: String,
    #[serde(rename = "error_message")]
    pub error_message: String,
    #[serde(rename = "download_url_expires_at")]
    pub download_url_expires_at: String,
    #[serde(rename = "expires_at")]
    pub expires_at: String,
}

impl HarvestStatusResponseSchemaNullable {
    #[must_use] 
    pub fn new(
        harvest_id: String,
        status: models::HarvestStatusEnum,
        created_at: String,
        started_at: String,
        completed_at: String,
        failed_at: String,
        file_size: String,
        progress_percent: f64,
        progress_step: String,
        error_message: String,
        download_url_expires_at: String,
        expires_at: String,
    ) -> HarvestStatusResponseSchemaNullable {
        HarvestStatusResponseSchemaNullable {
            harvest_id,
            status,
            created_at,
            started_at,
            completed_at,
            failed_at,
            file_size,
            progress_percent,
            progress_step,
            error_message,
            download_url_expires_at,
            expires_at,
        }
    }
}
