/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IndexRefreshStatusResponse {
    IndexRefreshStatusResponseOneOf(Box<models::IndexRefreshStatusResponseOneOf>),
    IndexRefreshStatusResponseOneOf1(Box<models::IndexRefreshStatusResponseOneOf1>),
}

impl Default for IndexRefreshStatusResponse {
    fn default() -> Self {
        Self::IndexRefreshStatusResponseOneOf(Default::default())
    }
}
/// Current status of the index refresh job
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Status {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

