/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexRefreshStatusResponseOneOf1 {
    /// Current status of the index refresh job
    #[serde(rename = "status")]
    pub status: Status,
    /// Type of index being refreshed
    #[serde(rename = "index_type")]
    pub index_type: String,
    /// Total number of items to index
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// Number of items indexed so far
    #[serde(rename = "indexed", skip_serializing_if = "Option::is_none")]
    pub indexed: Option<f64>,
    /// ISO 8601 timestamp when the job started
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// ISO 8601 timestamp when the job completed
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    /// ISO 8601 timestamp when the job failed
    #[serde(rename = "failed_at", skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<String>,
    /// Error message if the job failed
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl IndexRefreshStatusResponseOneOf1 {
    #[must_use] 
    pub fn new(status: Status, index_type: String) -> IndexRefreshStatusResponseOneOf1 {
        IndexRefreshStatusResponseOneOf1 {
            status,
            index_type,
            total: None,
            indexed: None,
            started_at: None,
            completed_at: None,
            failed_at: None,
            error: None,
        }
    }
}
/// Current status of the index refresh job
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Status {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

