/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexRefreshStatusResponseOneOf {
    /// Job was not found
    #[serde(rename = "status")]
    pub status: Status,
}

impl IndexRefreshStatusResponseOneOf {
    #[must_use] 
    pub fn new(status: Status) -> IndexRefreshStatusResponseOneOf {
        IndexRefreshStatusResponseOneOf { status }
    }
}
/// Job was not found
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Status {
    #[serde(rename = "not_found")]
    #[default]
    NotFound,
}

