/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceConfigUpdateRequestSso {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "display_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(
        rename = "issuer",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub issuer: Option<Option<String>>,
    #[serde(
        rename = "authorization_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorization_url: Option<Option<String>>,
    #[serde(
        rename = "token_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token_url: Option<Option<String>>,
    #[serde(
        rename = "userinfo_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub userinfo_url: Option<Option<String>>,
    #[serde(
        rename = "jwks_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub jwks_url: Option<Option<String>>,
    #[serde(
        rename = "client_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<String>>,
    #[serde(
        rename = "client_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_secret: Option<Option<String>>,
    #[serde(
        rename = "scope",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scope: Option<Option<String>>,
    #[serde(rename = "allowed_domains", skip_serializing_if = "Option::is_none")]
    pub allowed_domains: Option<Vec<String>>,
    #[serde(rename = "auto_provision", skip_serializing_if = "Option::is_none")]
    pub auto_provision: Option<bool>,
    #[serde(
        rename = "redirect_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redirect_uri: Option<Option<String>>,
}

impl InstanceConfigUpdateRequestSso {
    #[must_use]
    pub fn new() -> InstanceConfigUpdateRequestSso {
        InstanceConfigUpdateRequestSso {
            enabled: None,
            display_name: None,
            issuer: None,
            authorization_url: None,
            token_url: None,
            userinfo_url: None,
            jwks_url: None,
            client_id: None,
            client_secret: None,
            scope: None,
            allowed_domains: None,
            auto_provision: None,
            redirect_uri: None,
        }
    }
}
