/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceConfigUpdateRequest {
    #[serde(
        rename = "manual_review_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub manual_review_enabled: Option<bool>,
    #[serde(
        rename = "manual_review_schedule_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub manual_review_schedule_enabled: Option<bool>,
    #[serde(
        rename = "manual_review_schedule_start_hour_utc",
        skip_serializing_if = "Option::is_none"
    )]
    pub manual_review_schedule_start_hour_utc: Option<i32>,
    #[serde(
        rename = "manual_review_schedule_end_hour_utc",
        skip_serializing_if = "Option::is_none"
    )]
    pub manual_review_schedule_end_hour_utc: Option<i32>,
    #[serde(
        rename = "registration_alerts_webhook_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub registration_alerts_webhook_url: Option<Option<String>>,
    #[serde(
        rename = "system_alerts_webhook_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub system_alerts_webhook_url: Option<Option<String>>,
    #[serde(rename = "sso", skip_serializing_if = "Option::is_none")]
    pub sso: Option<Box<models::InstanceConfigUpdateRequestSso>>,
}

impl InstanceConfigUpdateRequest {
    #[must_use]
    pub fn new() -> InstanceConfigUpdateRequest {
        InstanceConfigUpdateRequest {
            manual_review_enabled: None,
            manual_review_schedule_enabled: None,
            manual_review_schedule_start_hour_utc: None,
            manual_review_schedule_end_hour_utc: None,
            registration_alerts_webhook_url: None,
            system_alerts_webhook_url: None,
            sso: None,
        }
    }
}
