/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InviteResponseSchema {
    GuildInviteResponse(Box<models::GuildInviteResponse>),
    GroupDmInviteResponse(Box<models::GroupDmInviteResponse>),
    PackInviteResponse(Box<models::PackInviteResponse>),
}

impl Default for InviteResponseSchema {
    fn default() -> Self {
        Self::GuildInviteResponse(Default::default())
    }
}
/// The type of invite (guild)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Type {
    #[serde(rename = "0")]
    #[default]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

