/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `LimitConfigUpdateRequestLimitConfig` : New limit configuration snapshot
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitConfigUpdateRequestLimitConfig {
    /// Trait definitions used by rules
    #[serde(rename = "traitDefinitions", skip_serializing_if = "Option::is_none")]
    pub trait_definitions: Option<Vec<String>>,
    /// Limit rules
    #[serde(rename = "rules")]
    pub rules: Vec<models::LimitConfigUpdateRequestLimitConfigRulesInner>,
}

impl LimitConfigUpdateRequestLimitConfig {
    /// New limit configuration snapshot
    #[must_use] 
    pub fn new(
        rules: Vec<models::LimitConfigUpdateRequestLimitConfigRulesInner>,
    ) -> LimitConfigUpdateRequestLimitConfig {
        LimitConfigUpdateRequestLimitConfig {
            trait_definitions: None,
            rules,
        }
    }
}
