/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitFilterResponse {
    /// Trait filters for this limit rule
    #[serde(rename = "traits", skip_serializing_if = "Option::is_none")]
    pub traits: Option<Vec<String>>,
    /// Guild feature filters for this limit rule
    #[serde(rename = "guildFeatures", skip_serializing_if = "Option::is_none")]
    pub guild_features: Option<Vec<String>>,
}

impl LimitFilterResponse {
    #[must_use]
    pub fn new() -> LimitFilterResponse {
        LimitFilterResponse {
            traits: None,
            guild_features: None,
        }
    }
}
