/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitConfigGetResponseLimitConfig {
    #[serde(rename = "traitDefinitions")]
    pub trait_definitions: Vec<String>,
    #[serde(rename = "rules")]
    pub rules: Vec<models::LimitConfigGetResponseLimitConfigRulesInner>,
}

impl LimitConfigGetResponseLimitConfig {
    #[must_use] 
    pub fn new(
        trait_definitions: Vec<String>,
        rules: Vec<models::LimitConfigGetResponseLimitConfigRulesInner>,
    ) -> LimitConfigGetResponseLimitConfig {
        LimitConfigGetResponseLimitConfig {
            trait_definitions,
            rules,
        }
    }
}
