/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitConfigGetResponse {
    #[serde(rename = "limit_config")]
    pub limit_config: Box<models::LimitConfigGetResponseLimitConfig>,
    #[serde(rename = "limit_config_json")]
    pub limit_config_json: String,
    #[serde(rename = "self_hosted")]
    pub self_hosted: bool,
    #[serde(rename = "defaults")]
    pub defaults: std::collections::HashMap<String, std::collections::HashMap<String, f64>>,
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, models::LimitConfigGetResponseMetadataValue>,
    #[serde(rename = "categories")]
    pub categories: std::collections::HashMap<String, String>,
    #[serde(rename = "limit_keys")]
    pub limit_keys: Vec<String>,
    #[serde(rename = "bounds", skip_serializing_if = "Option::is_none")]
    pub bounds:
        Option<std::collections::HashMap<String, models::LimitConfigGetResponseBoundsValue>>,
}

impl LimitConfigGetResponse {
    #[must_use] 
    pub fn new(
        limit_config: models::LimitConfigGetResponseLimitConfig,
        limit_config_json: String,
        self_hosted: bool,
        defaults: std::collections::HashMap<String, std::collections::HashMap<String, f64>>,
        metadata: std::collections::HashMap<String, models::LimitConfigGetResponseMetadataValue>,
        categories: std::collections::HashMap<String, String>,
        limit_keys: Vec<String>,
    ) -> LimitConfigGetResponse {
        LimitConfigGetResponse {
            limit_config: Box::new(limit_config),
            limit_config_json,
            self_hosted,
            defaults,
            metadata,
            categories,
            limit_keys,
            bounds: None,
        }
    }
}
