/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVoiceRegionsRequest {
    /// Whether to include voice servers in the response
    #[serde(rename = "include_servers", skip_serializing_if = "Option::is_none")]
    pub include_servers: Option<bool>,
}

impl ListVoiceRegionsRequest {
    #[must_use] 
    pub fn new() -> ListVoiceRegionsRequest {
        ListVoiceRegionsRequest {
            include_servers: None,
        }
    }
}
