/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListGuildMembersRequest {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}

impl ListGuildMembersRequest {
    #[must_use] 
    pub fn new(guild_id: String) -> ListGuildMembersRequest {
        ListGuildMembersRequest {
            guild_id,
            limit: None,
            offset: None,
        }
    }
}
