/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListGuildMembersResponse {
    #[serde(rename = "members")]
    pub members: Vec<models::GuildMemberResponse>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
}

impl ListGuildMembersResponse {
    #[must_use]
    pub fn new(
        members: Vec<models::GuildMemberResponse>,
        total: i32,
        limit: i32,
        offset: i32,
    ) -> ListGuildMembersResponse {
        ListGuildMembersResponse {
            members,
            total,
            limit,
            offset,
        }
    }
}
