/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUserDmChannelsRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "before", skip_serializing_if = "Option::is_none")]
    pub before: Option<String>,
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
    /// Maximum number of DM channels to return
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl ListUserDmChannelsRequest {
    #[must_use]
    pub fn new(user_id: String) -> ListUserDmChannelsRequest {
        ListUserDmChannelsRequest {
            user_id,
            before: None,
            after: None,
            limit: None,
        }
    }
}
