/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogoutAuthSessionsRequest {
    /// Array of session ID hashes to log out (max 100)
    #[serde(rename = "session_id_hashes")]
    pub session_id_hashes: Vec<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl LogoutAuthSessionsRequest {
    #[must_use]
    pub fn new(session_id_hashes: Vec<String>) -> LogoutAuthSessionsRequest {
        LogoutAuthSessionsRequest {
            session_id_hashes,
            password: None,
        }
    }
}
