/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupUserByQueryRequest {
    #[serde(rename = "query")]
    pub query: String,
}

impl LookupUserByQueryRequest {
    #[must_use]
    pub fn new(query: String) -> LookupUserByQueryRequest {
        LookupUserByQueryRequest { query }
    }
}
