/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LookupUserRequest {
    LookupUserByQueryRequest(Box<models::LookupUserByQueryRequest>),
    LookupUserByIdsRequest(Box<models::LookupUserByIdsRequest>),
}

impl Default for LookupUserRequest {
    fn default() -> Self {
        Self::LookupUserByQueryRequest(Default::default())
    }
}
