/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupMessageResponseMessagesInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "author_id")]
    pub author_id: String,
    #[serde(rename = "author_username")]
    pub author_username: String,
    #[serde(rename = "author_discriminator")]
    pub author_discriminator: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "attachments")]
    pub attachments: Vec<models::LookupMessageResponseMessagesInnerAttachmentsInner>,
}

impl LookupMessageResponseMessagesInner {
    #[must_use] 
    pub fn new(
        id: String,
        channel_id: String,
        author_id: String,
        author_username: String,
        author_discriminator: String,
        content: String,
        timestamp: String,
        attachments: Vec<models::LookupMessageResponseMessagesInnerAttachmentsInner>,
    ) -> LookupMessageResponseMessagesInner {
        LookupMessageResponseMessagesInner {
            id,
            channel_id,
            author_id,
            author_username,
            author_discriminator,
            content,
            timestamp,
            attachments,
        }
    }
}
