/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupGuildResponseGuildRolesInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: i32,
    #[serde(rename = "position")]
    pub position: i32,
    /// The role permissions bitfield
    #[serde(rename = "permissions")]
    pub permissions: String,
    #[serde(rename = "hoist")]
    pub hoist: bool,
    #[serde(rename = "mentionable")]
    pub mentionable: bool,
}

impl LookupGuildResponseGuildRolesInner {
    #[must_use]
    pub fn new(
        id: String,
        name: String,
        color: i32,
        position: i32,
        permissions: String,
        hoist: bool,
        mentionable: bool,
    ) -> LookupGuildResponseGuildRolesInner {
        LookupGuildResponseGuildRolesInner {
            id,
            name,
            color,
            position,
            permissions,
            hoist,
            mentionable,
        }
    }
}
