/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `MessageContentType` : The type of content contained in a message
/// The type of content contained in a message
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum MessageContentType {
    #[serde(rename = "image")]
    #[default]
    Image,
    #[serde(rename = "sound")]
    Sound,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "file")]
    File,
    #[serde(rename = "sticker")]
    Sticker,
    #[serde(rename = "embed")]
    Embed,
    #[serde(rename = "link")]
    Link,
    #[serde(rename = "poll")]
    Poll,
    #[serde(rename = "snapshot")]
    Snapshot,
}

impl std::fmt::Display for MessageContentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Image => write!(f, "image"),
            Self::Sound => write!(f, "sound"),
            Self::Video => write!(f, "video"),
            Self::File => write!(f, "file"),
            Self::Sticker => write!(f, "sticker"),
            Self::Embed => write!(f, "embed"),
            Self::Link => write!(f, "link"),
            Self::Poll => write!(f, "poll"),
            Self::Snapshot => write!(f, "snapshot"),
        }
    }
}
