/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAttachmentResponse {
    /// The unique identifier for this attachment
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the attached file
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "content_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_type: Option<Option<String>>,
    #[serde(
        rename = "content_hash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_hash: Option<Option<String>>,
    /// The size of the attachment in bytes
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(
        rename = "url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub url: Option<Option<String>>,
    #[serde(
        rename = "proxy_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub proxy_url: Option<Option<String>>,
    #[serde(
        rename = "width",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub width: Option<Option<i32>>,
    #[serde(
        rename = "height",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub height: Option<Option<i32>>,
    #[serde(
        rename = "placeholder",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub placeholder: Option<Option<String>>,
    /// Attachment flags
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(
        rename = "nsfw",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nsfw: Option<Option<bool>>,
    #[serde(
        rename = "duration",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub duration: Option<Option<i32>>,
    #[serde(
        rename = "waveform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub waveform: Option<Option<String>>,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<String>>,
    #[serde(
        rename = "expired",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expired: Option<Option<bool>>,
}

impl MessageAttachmentResponse {
    #[must_use]
    pub fn new(id: String, filename: String, size: i32, flags: i32) -> MessageAttachmentResponse {
        MessageAttachmentResponse {
            id,
            filename,
            title: None,
            description: None,
            content_type: None,
            content_hash: None,
            size,
            url: None,
            proxy_url: None,
            width: None,
            height: None,
            placeholder: None,
            flags,
            nsfw: None,
            duration: None,
            waveform: None,
            expires_at: None,
            expired: None,
        }
    }
}
