/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageBaseResponseSchema {
    /// The unique identifier (snowflake) for this message
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the channel this message was sent in
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "author")]
    pub author: Box<models::UserPartialResponse>,
    #[serde(
        rename = "webhook_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub webhook_id: Option<Option<String>>,
    /// The type of message
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Message flags bitfield
    #[serde(rename = "flags")]
    pub flags: i32,
    /// The text content of the message
    #[serde(rename = "content")]
    pub content: String,
    /// The ISO 8601 timestamp of when the message was created
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(
        rename = "edited_timestamp",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub edited_timestamp: Option<Option<String>>,
    /// Whether the message is pinned
    #[serde(rename = "pinned")]
    pub pinned: bool,
    /// Whether the message mentions @everyone
    #[serde(rename = "mention_everyone")]
    pub mention_everyone: bool,
    /// Whether the message was sent as text-to-speech
    #[serde(rename = "tts", skip_serializing_if = "Option::is_none")]
    pub tts: Option<bool>,
    #[serde(
        rename = "mentions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mentions: Option<Option<Vec<models::UserPartialResponse>>>,
    #[serde(
        rename = "mention_roles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mention_roles: Option<Option<Vec<String>>>,
    #[serde(
        rename = "embeds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub embeds: Option<Option<Vec<models::MessageEmbedResponse>>>,
    #[serde(
        rename = "attachments",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachments: Option<Option<Vec<models::MessageAttachmentResponse>>>,
    #[serde(
        rename = "stickers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stickers: Option<Option<Vec<models::MessageStickerResponse>>>,
    #[serde(
        rename = "reactions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reactions: Option<Option<Vec<models::MessageReactionResponse>>>,
    #[serde(
        rename = "message_reference",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_reference: Option<Option<Box<models::MessageReferenceResponse>>>,
    #[serde(
        rename = "message_snapshots",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_snapshots: Option<Option<Vec<models::MessageSnapshotResponse>>>,
    #[serde(
        rename = "nonce",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nonce: Option<Option<String>>,
    #[serde(
        rename = "call",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub call: Option<Option<Box<models::MessageCallResponse>>>,
}

impl MessageBaseResponseSchema {
    #[must_use]
    pub fn new(
        id: String,
        channel_id: String,
        author: models::UserPartialResponse,
        r#type: Type,
        flags: i32,
        content: String,
        timestamp: String,
        pinned: bool,
        mention_everyone: bool,
    ) -> MessageBaseResponseSchema {
        MessageBaseResponseSchema {
            id,
            channel_id,
            author: Box::new(author),
            webhook_id: None,
            r#type,
            flags,
            content,
            timestamp,
            edited_timestamp: None,
            pinned,
            mention_everyone,
            tts: None,
            mentions: None,
            mention_roles: None,
            embeds: None,
            attachments: None,
            stickers: None,
            reactions: None,
            message_reference: None,
            message_snapshots: None,
            nonce: None,
            call: None,
        }
    }
}
/// The type of message
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Type {
    #[serde(rename = "0")]
    #[default]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "7")]
    Variant7,
    #[serde(rename = "19")]
    Variant19,
}
