/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageShredStatusResponse {
    MessageShredStatusNotFoundResponse(Box<models::MessageShredStatusNotFoundResponse>),
    MessageShredStatusProgressResponse(Box<models::MessageShredStatusProgressResponse>),
}

impl Default for MessageShredStatusResponse {
    fn default() -> Self {
        Self::MessageShredStatusNotFoundResponse(Default::default())
    }
}
/// Current message shred job status
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Status {
    #[serde(rename = "in_progress")]
    #[default]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}
