/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MyGuildMemberUpdateRequest {
    #[serde(
        rename = "nick",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nick: Option<Option<String>>,
    /// Base64-encoded image data
    #[serde_as(as = "super::DoubleOption<serde_with::base64::Base64>")]
    #[serde(rename = "avatar", default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<Vec<u8>>>,
    /// Base64-encoded image data
    #[serde_as(as = "super::DoubleOption<serde_with::base64::Base64>")]
    #[serde(rename = "banner", default, skip_serializing_if = "Option::is_none")]
    pub banner: Option<Option<Vec<u8>>>,
    #[serde(
        rename = "bio",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bio: Option<Option<String>>,
    #[serde(
        rename = "pronouns",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pronouns: Option<Option<String>>,
    #[serde(
        rename = "accent_color",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub accent_color: Option<Option<i32>>,
    /// Member profile flags
    #[serde(
        rename = "profile_flags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_flags: Option<Option<i32>>,
    /// Whether the member is muted in voice channels
    #[serde(rename = "mute", skip_serializing_if = "Option::is_none")]
    pub mute: Option<bool>,
    /// Whether the member is deafened in voice channels
    #[serde(rename = "deaf", skip_serializing_if = "Option::is_none")]
    pub deaf: Option<bool>,
    #[serde(
        rename = "communication_disabled_until",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub communication_disabled_until: Option<Option<String>>,
    #[serde(
        rename = "timeout_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout_reason: Option<Option<String>>,
    #[serde(
        rename = "channel_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub channel_id: Option<Option<String>>,
    #[serde(
        rename = "connection_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub connection_id: Option<Option<String>>,
}

impl MyGuildMemberUpdateRequest {
    #[must_use] 
    pub fn new() -> MyGuildMemberUpdateRequest {
        MyGuildMemberUpdateRequest {
            nick: None,
            avatar: None,
            banner: None,
            bio: None,
            pronouns: None,
            accent_color: None,
            profile_flags: None,
            mute: None,
            deaf: None,
            communication_disabled_until: None,
            timeout_reason: None,
            channel_id: None,
            connection_id: None,
        }
    }
}
