/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NcmecSubmissionStatusResponse {
    /// NCMEC submission status
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "ncmec_report_id", deserialize_with = "Option::deserialize")]
    pub ncmec_report_id: Option<String>,
    #[serde(rename = "submitted_at", deserialize_with = "Option::deserialize")]
    pub submitted_at: Option<String>,
    #[serde(
        rename = "submitted_by_admin_id",
        deserialize_with = "Option::deserialize"
    )]
    pub submitted_by_admin_id: Option<String>,
    #[serde(rename = "failure_reason", deserialize_with = "Option::deserialize")]
    pub failure_reason: Option<String>,
}

impl NcmecSubmissionStatusResponse {
    #[must_use]
    pub fn new(
        status: Status,
        ncmec_report_id: Option<String>,
        submitted_at: Option<String>,
        submitted_by_admin_id: Option<String>,
        failure_reason: Option<String>,
    ) -> NcmecSubmissionStatusResponse {
        NcmecSubmissionStatusResponse {
            status,
            ncmec_report_id,
            submitted_at,
            submitted_by_admin_id,
            failure_reason,
        }
    }
}
/// NCMEC submission status
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Status {
    #[serde(rename = "not_submitted")]
    #[default]
    NotSubmitted,
    #[serde(rename = "submitted")]
    Submitted,
    #[serde(rename = "failed")]
    Failed,
}
