/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeStatsResponse {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "sessions")]
    pub sessions: i32,
    #[serde(rename = "guilds")]
    pub guilds: i32,
    #[serde(rename = "presences")]
    pub presences: i32,
    #[serde(rename = "calls")]
    pub calls: i32,
    #[serde(rename = "memory")]
    pub memory: Box<models::NodeStatsResponseMemory>,
    #[serde(rename = "process_count")]
    pub process_count: i32,
    #[serde(rename = "process_limit")]
    pub process_limit: i32,
    #[serde(rename = "uptime_seconds")]
    pub uptime_seconds: i32,
}

impl NodeStatsResponse {
    #[must_use] 
    pub fn new(
        status: String,
        sessions: i32,
        guilds: i32,
        presences: i32,
        calls: i32,
        memory: models::NodeStatsResponseMemory,
        process_count: i32,
        process_limit: i32,
        uptime_seconds: i32,
    ) -> NodeStatsResponse {
        NodeStatsResponse {
            status,
            sessions,
            guilds,
            presences,
            calls,
            memory: Box::new(memory),
            process_count,
            process_limit,
            uptime_seconds,
        }
    }
}
