/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2AuthorizationResponse {
    #[serde(rename = "application")]
    pub application: Box<models::OAuth2AuthorizationResponseApplication>,
    /// The list of granted `OAuth2` scopes
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    /// The timestamp when the authorization was granted
    #[serde(rename = "authorized_at")]
    pub authorized_at: String,
}

impl OAuth2AuthorizationResponse {
    #[must_use]
    pub fn new(
        application: models::OAuth2AuthorizationResponseApplication,
        scopes: Vec<String>,
        authorized_at: String,
    ) -> OAuth2AuthorizationResponse {
        OAuth2AuthorizationResponse {
            application: Box::new(application),
            scopes,
            authorized_at,
        }
    }
}
