/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `OAuth2MeResponseUser` : The user associated with the token
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2MeResponseUser {
    /// The unique identifier of the user
    #[serde(rename = "id")]
    pub id: String,
    /// The username of the user
    #[serde(rename = "username")]
    pub username: String,
    /// The discriminator of the user
    #[serde(rename = "discriminator")]
    pub discriminator: String,
    #[serde(rename = "global_name", deserialize_with = "Option::deserialize")]
    pub global_name: Option<String>,
    #[serde(rename = "avatar", deserialize_with = "Option::deserialize")]
    pub avatar: Option<String>,
    #[serde(rename = "avatar_color", deserialize_with = "Option::deserialize")]
    pub avatar_color: Option<i32>,
    /// Whether the user is a bot
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<bool>,
    /// Whether the user is a system user
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<bool>,
    /// The public flags on the user account
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(
        rename = "verified",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub verified: Option<Option<bool>>,
}

impl OAuth2MeResponseUser {
    /// The user associated with the token
    #[must_use] 
    pub fn new(
        id: String,
        username: String,
        discriminator: String,
        global_name: Option<String>,
        avatar: Option<String>,
        avatar_color: Option<i32>,
        flags: i32,
    ) -> OAuth2MeResponseUser {
        OAuth2MeResponseUser {
            id,
            username,
            discriminator,
            global_name,
            avatar,
            avatar_color,
            bot: None,
            system: None,
            flags,
            email: None,
            verified: None,
        }
    }
}
