/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2IntrospectResponse {
    /// Whether the token is currently active
    #[serde(rename = "active")]
    pub active: bool,
    /// The space-separated list of scopes
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The username of the token owner
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// The type of token
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
    #[serde(rename = "exp", skip_serializing_if = "Option::is_none")]
    pub exp: Option<i32>,
    #[serde(rename = "iat", skip_serializing_if = "Option::is_none")]
    pub iat: Option<i32>,
    #[serde(rename = "sub", skip_serializing_if = "Option::is_none")]
    pub sub: Option<String>,
}

impl OAuth2IntrospectResponse {
    #[must_use]
    pub fn new(active: bool) -> OAuth2IntrospectResponse {
        OAuth2IntrospectResponse {
            active,
            scope: None,
            client_id: None,
            username: None,
            token_type: None,
            exp: None,
            iat: None,
            sub: None,
        }
    }
}
