/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2UserInfoResponse {
    /// The subject identifier of the user
    #[serde(rename = "sub")]
    pub sub: String,
    /// The unique identifier of the user
    #[serde(rename = "id")]
    pub id: String,
    /// The username of the user
    #[serde(rename = "username")]
    pub username: String,
    /// The discriminator of the user
    #[serde(rename = "discriminator")]
    pub discriminator: String,
    #[serde(rename = "global_name", deserialize_with = "Option::deserialize")]
    pub global_name: Option<String>,
    #[serde(rename = "avatar", deserialize_with = "Option::deserialize")]
    pub avatar: Option<String>,
    #[serde(
        rename = "email",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email: Option<Option<String>>,
    #[serde(
        rename = "verified",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub verified: Option<Option<bool>>,
    /// The public flags on the user account
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
}

impl OAuth2UserInfoResponse {
    #[must_use]
    pub fn new(
        sub: String,
        id: String,
        username: String,
        discriminator: String,
        global_name: Option<String>,
        avatar: Option<String>,
    ) -> OAuth2UserInfoResponse {
        OAuth2UserInfoResponse {
            sub,
            id,
            username,
            discriminator,
            global_name,
            avatar,
            email: None,
            verified: None,
            flags: None,
        }
    }
}
