/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `PackDashboardResponseSticker` : Dashboard section for sticker packs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackDashboardResponseSticker {
    /// Maximum number of packs the user can install
    #[serde(rename = "installed_limit")]
    pub installed_limit: i32,
    /// Maximum number of packs the user can create
    #[serde(rename = "created_limit")]
    pub created_limit: i32,
    /// List of packs the user has installed
    #[serde(rename = "installed")]
    pub installed: Vec<models::PackSummaryResponse>,
    /// List of packs the user has created
    #[serde(rename = "created")]
    pub created: Vec<models::PackSummaryResponse>,
}

impl PackDashboardResponseSticker {
    /// Dashboard section for sticker packs
    #[must_use]
    pub fn new(
        installed_limit: i32,
        created_limit: i32,
        installed: Vec<models::PackSummaryResponse>,
        created: Vec<models::PackSummaryResponse>,
    ) -> PackDashboardResponseSticker {
        PackDashboardResponseSticker {
            installed_limit,
            created_limit,
            installed,
            created,
        }
    }
}
