/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordChangeStartResponse {
    /// Ticket for password change actions
    #[serde(rename = "ticket")]
    pub ticket: String,
    /// ISO8601 timestamp when the verification code expires
    #[serde(rename = "code_expires_at")]
    pub code_expires_at: String,
    #[serde(
        rename = "resend_available_at",
        deserialize_with = "Option::deserialize"
    )]
    pub resend_available_at: Option<String>,
}

impl PasswordChangeStartResponse {
    #[must_use]
    pub fn new(
        ticket: String,
        code_expires_at: String,
        resend_available_at: Option<String>,
    ) -> PasswordChangeStartResponse {
        PasswordChangeStartResponse {
            ticket,
            code_expires_at,
            resend_available_at,
        }
    }
}
