/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurgeGuildAssetErrorSchema {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "error")]
    pub error: String,
}

impl PurgeGuildAssetErrorSchema {
    #[must_use] 
    pub fn new(id: String, error: String) -> PurgeGuildAssetErrorSchema {
        PurgeGuildAssetErrorSchema { id, error }
    }
}
