/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushSubscribeRequest {
    /// The push subscription endpoint URL
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "keys")]
    pub keys: Box<models::PushSubscribeRequestKeys>,
    /// The user agent string
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
}

impl PushSubscribeRequest {
    #[must_use]
    pub fn new(endpoint: String, keys: models::PushSubscribeRequestKeys) -> PushSubscribeRequest {
        PushSubscribeRequest {
            endpoint,
            keys: Box::new(keys),
            user_agent: None,
        }
    }
}
