/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelationshipTypePutRequest {
    /// Type of relationship to create
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::RelationshipTypes>,
}

impl RelationshipTypePutRequest {
    #[must_use] 
    pub fn new() -> RelationshipTypePutRequest {
        RelationshipTypePutRequest { r#type: None }
    }
}
