/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReorderConnectionsRequest {
    /// Ordered list of connection IDs defining the new display order
    #[serde(rename = "connection_ids")]
    pub connection_ids: Vec<String>,
}

impl ReorderConnectionsRequest {
    #[must_use] 
    pub fn new(connection_ids: Vec<String>) -> ReorderConnectionsRequest {
        ReorderConnectionsRequest { connection_ids }
    }
}
