/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportGuildRequest {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "category")]
    pub category: models::GuildReportCategoryEnum,
    /// Additional context or details about the report
    #[serde(rename = "additional_info", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
}

impl ReportGuildRequest {
    #[must_use]
    pub fn new(guild_id: String, category: models::GuildReportCategoryEnum) -> ReportGuildRequest {
        ReportGuildRequest {
            guild_id,
            category,
            additional_info: None,
        }
    }
}
