/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportMessageRequest {
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "category")]
    pub category: models::MessageReportCategoryEnum,
    /// Additional context or details about the report
    #[serde(rename = "additional_info", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
}

impl ReportMessageRequest {
    #[must_use] 
    pub fn new(
        channel_id: String,
        message_id: String,
        category: models::MessageReportCategoryEnum,
    ) -> ReportMessageRequest {
        ReportMessageRequest {
            channel_id,
            message_id,
            category,
            additional_info: None,
        }
    }
}
