/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportUserRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "category")]
    pub category: models::UserReportCategoryEnum,
    /// Additional context or details about the report
    #[serde(rename = "additional_info", skip_serializing_if = "Option::is_none")]
    pub additional_info: Option<String>,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
}

impl ReportUserRequest {
    #[must_use] 
    pub fn new(user_id: String, category: models::UserReportCategoryEnum) -> ReportUserRequest {
        ReportUserRequest {
            user_id,
            category,
            additional_info: None,
            guild_id: None,
        }
    }
}
