/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledMessageResponseSchema {
    /// The unique identifier for this scheduled message
    #[serde(rename = "id")]
    pub id: String,
    /// The ID of the channel this message will be sent to
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    /// The ISO 8601 UTC timestamp when the message is scheduled to be sent
    #[serde(rename = "scheduled_at")]
    pub scheduled_at: String,
    /// The ISO 8601 timestamp in the user local timezone
    #[serde(rename = "scheduled_local_at")]
    pub scheduled_local_at: String,
    /// The IANA timezone identifier used for scheduling
    #[serde(rename = "timezone")]
    pub timezone: String,
    /// The current status of the scheduled message
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "status_reason", deserialize_with = "Option::deserialize")]
    pub status_reason: Option<String>,
    #[serde(rename = "payload")]
    pub payload: Box<models::ScheduledMessageResponseSchemaPayload>,
    /// The ISO 8601 timestamp when this scheduled message was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "invalidated_at", deserialize_with = "Option::deserialize")]
    pub invalidated_at: Option<String>,
}

impl ScheduledMessageResponseSchema {
    #[must_use]
    pub fn new(
        id: String,
        channel_id: String,
        scheduled_at: String,
        scheduled_local_at: String,
        timezone: String,
        status: Status,
        status_reason: Option<String>,
        payload: models::ScheduledMessageResponseSchemaPayload,
        created_at: String,
        invalidated_at: Option<String>,
    ) -> ScheduledMessageResponseSchema {
        ScheduledMessageResponseSchema {
            id,
            channel_id,
            scheduled_at,
            scheduled_local_at,
            timezone,
            status,
            status_reason,
            payload: Box::new(payload),
            created_at,
            invalidated_at,
        }
    }
}
/// The current status of the scheduled message
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Status {
    #[serde(rename = "pending")]
    #[default]
    Pending,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}
