/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleAccountDeletionRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Code indicating the reason for deletion
    #[serde(rename = "reason_code")]
    pub reason_code: i32,
    /// Public-facing reason for the deletion
    #[serde(rename = "public_reason", skip_serializing_if = "Option::is_none")]
    pub public_reason: Option<String>,
    /// Number of days until the account is deleted
    #[serde(
        rename = "days_until_deletion",
        skip_serializing_if = "Option::is_none"
    )]
    pub days_until_deletion: Option<i32>,
}

impl ScheduleAccountDeletionRequest {
    #[must_use]
    pub fn new(user_id: String, reason_code: i32) -> ScheduleAccountDeletionRequest {
        ScheduleAccountDeletionRequest {
            user_id,
            reason_code,
            public_reason: None,
            days_until_deletion: None,
        }
    }
}
