/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchAuditLogsRequest {
    /// Search query string
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "admin_user_id", skip_serializing_if = "Option::is_none")]
    pub admin_user_id: Option<String>,
    /// Filter by target entity ID (user, channel, role, invite code, etc.)
    #[serde(rename = "target_id", skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
    /// Field to sort audit logs by
    #[serde(rename = "sort_by", skip_serializing_if = "Option::is_none")]
    pub sort_by: Option<SortBy>,
    /// Sort order direction
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<SortOrder>,
    /// Maximum number of entries to return
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Number of entries to skip
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}

impl SearchAuditLogsRequest {
    #[must_use] 
    pub fn new() -> SearchAuditLogsRequest {
        SearchAuditLogsRequest {
            query: None,
            admin_user_id: None,
            target_id: None,
            sort_by: None,
            sort_order: None,
            limit: None,
            offset: None,
        }
    }
}
/// Field to sort audit logs by
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum SortBy {
    #[serde(rename = "createdAt")]
    #[default]
    CreatedAt,
    #[serde(rename = "relevance")]
    Relevance,
}

/// Sort order direction
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum SortOrder {
    #[serde(rename = "asc")]
    #[default]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

