/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetUserSystemStatusRequest {
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Whether the user should be marked as a system user
    #[serde(rename = "system")]
    pub system: bool,
}

impl SetUserSystemStatusRequest {
    #[must_use] 
    pub fn new(user_id: String, system: bool) -> SetUserSystemStatusRequest {
        SetUserSystemStatusRequest { user_id, system }
    }
}
