/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemDmJobResponse {
    /// Unique identifier for the job
    #[serde(rename = "job_id")]
    pub job_id: String,
    /// Current status of the system DM job
    #[serde(rename = "status")]
    pub status: Status,
    /// Message content being sent
    #[serde(rename = "content")]
    pub content: String,
    /// Total number of users targeted
    #[serde(rename = "target_count")]
    pub target_count: i32,
    /// Number of messages successfully sent
    #[serde(rename = "sent_count")]
    pub sent_count: i32,
    /// Number of messages that failed to send
    #[serde(rename = "failed_count")]
    pub failed_count: i32,
    /// ISO 8601 timestamp when the job was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(
        rename = "approved_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub approved_at: Option<Option<String>>,
    #[serde(
        rename = "registration_start",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub registration_start: Option<Option<String>>,
    #[serde(
        rename = "registration_end",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub registration_end: Option<Option<String>>,
    /// List of excluded guild IDs
    #[serde(rename = "excluded_guild_ids")]
    pub excluded_guild_ids: Vec<String>,
    #[serde(
        rename = "last_error",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_error: Option<Option<String>>,
}

impl SystemDmJobResponse {
    #[must_use] 
    pub fn new(
        job_id: String,
        status: Status,
        content: String,
        target_count: i32,
        sent_count: i32,
        failed_count: i32,
        created_at: String,
        excluded_guild_ids: Vec<String>,
    ) -> SystemDmJobResponse {
        SystemDmJobResponse {
            job_id,
            status,
            content,
            target_count,
            sent_count,
            failed_count,
            created_at,
            approved_at: None,
            registration_start: None,
            registration_end: None,
            excluded_guild_ids,
            last_error: None,
        }
    }
}
/// Current status of the system DM job
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
#[derive(Default)]
pub enum Status {
    #[serde(rename = "pending")]
    #[default]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

