/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenorGifResponse {
    /// The unique Tenor result id
    #[serde(rename = "id")]
    pub id: String,
    /// The title/description of the GIF
    #[serde(rename = "title")]
    pub title: String,
    /// The Tenor page URL for the GIF
    #[serde(rename = "url")]
    pub url: String,
    /// Direct URL to the GIF media file
    #[serde(rename = "src")]
    pub src: String,
    /// Proxied URL to the GIF media file
    #[serde(rename = "proxy_src")]
    pub proxy_src: String,
    /// Width of the GIF in pixels
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the GIF in pixels
    #[serde(rename = "height")]
    pub height: i32,
}

impl TenorGifResponse {
    #[must_use]
    pub fn new(
        id: String,
        title: String,
        url: String,
        src: String,
        proxy_src: String,
        width: i32,
        height: i32,
    ) -> TenorGifResponse {
        TenorGifResponse {
            id,
            title,
            url,
            src,
            proxy_src,
            width,
            height,
        }
    }
}
