/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenorFeaturedResponse {
    /// Array of featured GIFs
    #[serde(rename = "gifs")]
    pub gifs: Vec<models::TenorGifResponse>,
    /// Array of GIF categories
    #[serde(rename = "categories")]
    pub categories: Vec<models::TenorCategoryTagResponse>,
}

impl TenorFeaturedResponse {
    #[must_use] 
    pub fn new(
        gifs: Vec<models::TenorGifResponse>,
        categories: Vec<models::TenorCategoryTagResponse>,
    ) -> TenorFeaturedResponse {
        TenorFeaturedResponse { gifs, categories }
    }
}
