/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenorCategoryTagResponse {
    /// The category search term
    #[serde(rename = "name")]
    pub name: String,
    /// URL to the category preview image
    #[serde(rename = "src")]
    pub src: String,
    /// Proxied URL to the category preview image
    #[serde(rename = "proxy_src")]
    pub proxy_src: String,
}

impl TenorCategoryTagResponse {
    #[must_use]
    pub fn new(name: String, src: String, proxy_src: String) -> TenorCategoryTagResponse {
        TenorCategoryTagResponse {
            name,
            src,
            proxy_src,
        }
    }
}
