/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGuildFeaturesRequest {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    /// Guild features to add
    #[serde(rename = "add_features", skip_serializing_if = "Option::is_none")]
    pub add_features: Option<Vec<String>>,
    /// Guild features to remove
    #[serde(rename = "remove_features", skip_serializing_if = "Option::is_none")]
    pub remove_features: Option<Vec<String>>,
}

impl UpdateGuildFeaturesRequest {
    #[must_use]
    pub fn new(guild_id: String) -> UpdateGuildFeaturesRequest {
        UpdateGuildFeaturesRequest {
            guild_id,
            add_features: None,
            remove_features: None,
        }
    }
}
