/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadChunkResponse {
    /// The `ETag` of the uploaded chunk
    #[serde(rename = "etag")]
    pub etag: String,
}

impl UploadChunkResponse {
    #[must_use] 
    pub fn new(etag: String) -> UploadChunkResponse {
        UploadChunkResponse { etag }
    }
}
