/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfileFullResponse {
    #[serde(rename = "user")]
    pub user: Box<models::UserProfileFullResponseUser>,
    #[serde(rename = "user_profile")]
    pub user_profile: Box<models::UserProfileFullResponseUserProfile>,
    #[serde(rename = "guild_member", skip_serializing_if = "Option::is_none")]
    pub guild_member: Option<Box<models::GuildMemberResponse>>,
    #[serde(
        rename = "guild_member_profile",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub guild_member_profile:
        Option<Option<Box<models::UserProfileFullResponseGuildMemberProfile>>>,
    /// The type of premium subscription
    #[serde(rename = "premium_type", skip_serializing_if = "Option::is_none")]
    pub premium_type: Option<models::UserPremiumTypes>,
    /// ISO8601 timestamp of when premium was activated
    #[serde(rename = "premium_since", skip_serializing_if = "Option::is_none")]
    pub premium_since: Option<String>,
    #[serde(
        rename = "premium_lifetime_sequence",
        skip_serializing_if = "Option::is_none"
    )]
    pub premium_lifetime_sequence: Option<i32>,
    /// Array of mutual friends
    #[serde(rename = "mutual_friends", skip_serializing_if = "Option::is_none")]
    pub mutual_friends: Option<Vec<models::UserPartialResponse>>,
    /// Array of mutual guilds
    #[serde(rename = "mutual_guilds", skip_serializing_if = "Option::is_none")]
    pub mutual_guilds: Option<Vec<models::MutualGuildResponse>>,
    /// Array of verified external connections
    #[serde(rename = "connected_accounts", skip_serializing_if = "Option::is_none")]
    pub connected_accounts: Option<Vec<models::ConnectionResponse>>,
}

impl UserProfileFullResponse {
    #[must_use] 
    pub fn new(
        user: models::UserProfileFullResponseUser,
        user_profile: models::UserProfileFullResponseUserProfile,
    ) -> UserProfileFullResponse {
        UserProfileFullResponse {
            user: Box::new(user),
            user_profile: Box::new(user_profile),
            guild_member: None,
            guild_member_profile: None,
            premium_type: None,
            premium_since: None,
            premium_lifetime_sequence: None,
            mutual_friends: None,
            mutual_guilds: None,
            connected_accounts: None,
        }
    }
}
