/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPrivateResponse {
    /// The unique identifier (snowflake) for this user
    #[serde(rename = "id")]
    pub id: String,
    /// The username of the user, not unique across the platform
    #[serde(rename = "username")]
    pub username: String,
    /// The four-digit discriminator tag of the user
    #[serde(rename = "discriminator")]
    pub discriminator: String,
    #[serde(rename = "global_name", deserialize_with = "Option::deserialize")]
    pub global_name: Option<String>,
    #[serde(rename = "avatar", deserialize_with = "Option::deserialize")]
    pub avatar: Option<String>,
    #[serde(rename = "avatar_color", deserialize_with = "Option::deserialize")]
    pub avatar_color: Option<i32>,
    /// Whether the user is a bot account
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<bool>,
    /// Whether the user is an official system user
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<bool>,
    /// The public flags on the user account
    #[serde(rename = "flags")]
    pub flags: i32,
    /// Whether the user has staff permissions
    #[serde(rename = "is_staff")]
    pub is_staff: bool,
    /// Access control list entries for the user
    #[serde(rename = "acls")]
    pub acls: Vec<String>,
    /// Special traits assigned to the user account
    #[serde(rename = "traits")]
    pub traits: Vec<String>,
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<String>,
    /// Whether the current email address is marked as bounced by the mail provider
    #[serde(rename = "email_bounced", skip_serializing_if = "Option::is_none")]
    pub email_bounced: Option<bool>,
    #[serde(rename = "phone", deserialize_with = "Option::deserialize")]
    pub phone: Option<String>,
    #[serde(rename = "bio", deserialize_with = "Option::deserialize")]
    pub bio: Option<String>,
    #[serde(rename = "pronouns", deserialize_with = "Option::deserialize")]
    pub pronouns: Option<String>,
    #[serde(rename = "accent_color", deserialize_with = "Option::deserialize")]
    pub accent_color: Option<i32>,
    #[serde(rename = "banner", deserialize_with = "Option::deserialize")]
    pub banner: Option<String>,
    #[serde(rename = "banner_color", deserialize_with = "Option::deserialize")]
    pub banner_color: Option<i32>,
    /// Whether multi-factor authentication is enabled
    #[serde(rename = "mfa_enabled")]
    pub mfa_enabled: bool,
    /// The types of authenticators configured for MFA
    #[serde(
        rename = "authenticator_types",
        skip_serializing_if = "Option::is_none"
    )]
    pub authenticator_types: Option<Vec<models::UserAuthenticatorTypes>>,
    /// Whether the email address has been verified
    #[serde(rename = "verified")]
    pub verified: bool,
    /// The type of premium subscription
    #[serde(rename = "premium_type", deserialize_with = "Option::deserialize")]
    pub premium_type: Option<models::UserPremiumTypes>,
    #[serde(rename = "premium_since", deserialize_with = "Option::deserialize")]
    pub premium_since: Option<String>,
    #[serde(rename = "premium_until", deserialize_with = "Option::deserialize")]
    pub premium_until: Option<String>,
    /// Whether premium is set to cancel at the end of the billing period
    #[serde(rename = "premium_will_cancel")]
    pub premium_will_cancel: bool,
    #[serde(
        rename = "premium_billing_cycle",
        deserialize_with = "Option::deserialize"
    )]
    pub premium_billing_cycle: Option<String>,
    #[serde(
        rename = "premium_lifetime_sequence",
        deserialize_with = "Option::deserialize"
    )]
    pub premium_lifetime_sequence: Option<i32>,
    /// Whether the premium badge is hidden on the profile
    #[serde(rename = "premium_badge_hidden")]
    pub premium_badge_hidden: bool,
    /// Whether the premium badge shows a masked appearance
    #[serde(rename = "premium_badge_masked")]
    pub premium_badge_masked: bool,
    /// Whether the premium start timestamp is hidden
    #[serde(rename = "premium_badge_timestamp_hidden")]
    pub premium_badge_timestamp_hidden: bool,
    /// Whether the lifetime sequence number is hidden
    #[serde(rename = "premium_badge_sequence_hidden")]
    pub premium_badge_sequence_hidden: bool,
    /// Whether premium purchases are disabled for this account
    #[serde(rename = "premium_purchase_disabled")]
    pub premium_purchase_disabled: bool,
    /// Whether premium features are enabled via override
    #[serde(rename = "premium_enabled_override")]
    pub premium_enabled_override: bool,
    #[serde(
        rename = "password_last_changed_at",
        deserialize_with = "Option::deserialize"
    )]
    pub password_last_changed_at: Option<String>,
    #[serde(rename = "required_actions", deserialize_with = "Option::deserialize")]
    pub required_actions: Option<Vec<String>>,
    /// Whether the user is allowed to view NSFW content
    #[serde(rename = "nsfw_allowed")]
    pub nsfw_allowed: bool,
    /// Whether the user has dismissed the premium onboarding flow
    #[serde(rename = "has_dismissed_premium_onboarding")]
    pub has_dismissed_premium_onboarding: bool,
    /// Whether the user has ever made a purchase
    #[serde(rename = "has_ever_purchased")]
    pub has_ever_purchased: bool,
    /// Whether there are unread items in the gift inventory
    #[serde(rename = "has_unread_gift_inventory")]
    pub has_unread_gift_inventory: bool,
    /// The number of unread gift inventory items
    #[serde(rename = "unread_gift_inventory_count")]
    pub unread_gift_inventory_count: i32,
    /// Whether the user has ever used the mobile client
    #[serde(rename = "used_mobile_client")]
    pub used_mobile_client: bool,
    #[serde(
        rename = "pending_bulk_message_deletion",
        deserialize_with = "Option::deserialize"
    )]
    pub pending_bulk_message_deletion:
        Option<Box<models::UserPrivateResponsePendingBulkMessageDeletion>>,
}

impl UserPrivateResponse {
    #[must_use]
    pub fn new(
        id: String,
        username: String,
        discriminator: String,
        global_name: Option<String>,
        avatar: Option<String>,
        avatar_color: Option<i32>,
        flags: i32,
        is_staff: bool,
        acls: Vec<String>,
        traits: Vec<String>,
        email: Option<String>,
        phone: Option<String>,
        bio: Option<String>,
        pronouns: Option<String>,
        accent_color: Option<i32>,
        banner: Option<String>,
        banner_color: Option<i32>,
        mfa_enabled: bool,
        verified: bool,
        premium_type: Option<models::UserPremiumTypes>,
        premium_since: Option<String>,
        premium_until: Option<String>,
        premium_will_cancel: bool,
        premium_billing_cycle: Option<String>,
        premium_lifetime_sequence: Option<i32>,
        premium_badge_hidden: bool,
        premium_badge_masked: bool,
        premium_badge_timestamp_hidden: bool,
        premium_badge_sequence_hidden: bool,
        premium_purchase_disabled: bool,
        premium_enabled_override: bool,
        password_last_changed_at: Option<String>,
        required_actions: Option<Vec<String>>,
        nsfw_allowed: bool,
        has_dismissed_premium_onboarding: bool,
        has_ever_purchased: bool,
        has_unread_gift_inventory: bool,
        unread_gift_inventory_count: i32,
        used_mobile_client: bool,
        pending_bulk_message_deletion: Option<
            models::UserPrivateResponsePendingBulkMessageDeletion,
        >,
    ) -> UserPrivateResponse {
        UserPrivateResponse {
            id,
            username,
            discriminator,
            global_name,
            avatar,
            avatar_color,
            bot: None,
            system: None,
            flags,
            is_staff,
            acls,
            traits,
            email,
            email_bounced: None,
            phone,
            bio,
            pronouns,
            accent_color,
            banner,
            banner_color,
            mfa_enabled,
            authenticator_types: None,
            verified,
            premium_type,
            premium_since,
            premium_until,
            premium_will_cancel,
            premium_billing_cycle,
            premium_lifetime_sequence,
            premium_badge_hidden,
            premium_badge_masked,
            premium_badge_timestamp_hidden,
            premium_badge_sequence_hidden,
            premium_purchase_disabled,
            premium_enabled_override,
            password_last_changed_at,
            required_actions,
            nsfw_allowed,
            has_dismissed_premium_onboarding,
            has_ever_purchased,
            has_unread_gift_inventory,
            unread_gift_inventory_count,
            used_mobile_client,
            pending_bulk_message_deletion: pending_bulk_message_deletion.map(Box::new),
        }
    }
}
