/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGuildSettingsUpdateRequestChannelOverridesValue {
    /// Channel category collapsed
    #[serde(rename = "collapsed")]
    pub collapsed: bool,
    /// Channel notification level
    #[serde(rename = "message_notifications")]
    pub message_notifications: models::UserNotificationSettings,
    /// Channel muted
    #[serde(rename = "muted")]
    pub muted: bool,
    #[serde(
        rename = "mute_config",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mute_config: Option<Option<Box<models::UserGuildSettingsUpdateRequestMuteConfig>>>,
}

impl UserGuildSettingsUpdateRequestChannelOverridesValue {
    #[must_use] 
    pub fn new(
        collapsed: bool,
        message_notifications: models::UserNotificationSettings,
        muted: bool,
    ) -> UserGuildSettingsUpdateRequestChannelOverridesValue {
        UserGuildSettingsUpdateRequestChannelOverridesValue {
            collapsed,
            message_notifications,
            muted,
            mute_config: None,
        }
    }
}
