/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `UserSettingsUpdateRequestStatusResetsAt` : When status resets
/// When status resets
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UserSettingsUpdateRequestStatusResetsAt {
    String(String),
    Integer(i64),
}

impl Default for UserSettingsUpdateRequestStatusResetsAt {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
