/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGuildSettingsResponseChannelOverridesValue {
    /// Whether the channel category is collapsed in the sidebar
    #[serde(rename = "collapsed")]
    pub collapsed: bool,
    /// The notification level override for this channel
    #[serde(rename = "message_notifications")]
    pub message_notifications: models::UserNotificationSettings,
    /// Whether notifications are muted for this channel
    #[serde(rename = "muted")]
    pub muted: bool,
    #[serde(rename = "mute_config", deserialize_with = "Option::deserialize")]
    pub mute_config: Option<Box<models::UserGuildSettingsResponseMuteConfig>>,
}

impl UserGuildSettingsResponseChannelOverridesValue {
    #[must_use] 
    pub fn new(
        collapsed: bool,
        message_notifications: models::UserNotificationSettings,
        muted: bool,
        mute_config: Option<models::UserGuildSettingsResponseMuteConfig>,
    ) -> UserGuildSettingsResponseChannelOverridesValue {
        UserGuildSettingsResponseChannelOverridesValue {
            collapsed,
            message_notifications,
            muted,
            mute_config: mute_config.map(Box::new),
        }
    }
}
