/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsResponse {
    /// The current online status of the user
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "status_resets_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_resets_at: Option<Option<String>>,
    #[serde(
        rename = "status_resets_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_resets_to: Option<Option<String>>,
    /// The UI theme preference
    #[serde(rename = "theme")]
    pub theme: String,
    #[serde(rename = "locale")]
    pub locale: models::Locale,
    /// Guild IDs where direct messages are restricted
    #[serde(rename = "restricted_guilds")]
    pub restricted_guilds: Vec<String>,
    /// Guild IDs where bot direct messages are restricted
    #[serde(rename = "bot_restricted_guilds")]
    pub bot_restricted_guilds: Vec<String>,
    /// Whether new guilds have DM restrictions by default
    #[serde(rename = "default_guilds_restricted")]
    pub default_guilds_restricted: bool,
    /// Whether new guilds have bot DM restrictions by default
    #[serde(rename = "bot_default_guilds_restricted")]
    pub bot_default_guilds_restricted: bool,
    /// Whether to display attachments inline in chat
    #[serde(rename = "inline_attachment_media")]
    pub inline_attachment_media: bool,
    /// Whether to display embed media inline in chat
    #[serde(rename = "inline_embed_media")]
    pub inline_embed_media: bool,
    /// Whether GIFs auto-play in chat
    #[serde(rename = "gif_auto_play")]
    pub gif_auto_play: bool,
    /// Whether to render message embeds
    #[serde(rename = "render_embeds")]
    pub render_embeds: bool,
    /// Whether to display reactions on messages
    #[serde(rename = "render_reactions")]
    pub render_reactions: bool,
    /// Whether to animate custom emoji
    #[serde(rename = "animate_emoji")]
    pub animate_emoji: bool,
    /// Sticker animation preference setting
    #[serde(rename = "animate_stickers")]
    pub animate_stickers: models::StickerAnimationOptions,
    /// Spoiler rendering preference setting
    #[serde(rename = "render_spoilers")]
    pub render_spoilers: models::RenderSpoilers,
    /// Whether to use compact message display mode
    #[serde(rename = "message_display_compact")]
    pub message_display_compact: bool,
    /// Friend source flags
    #[serde(rename = "friend_source_flags")]
    pub friend_source_flags: i32,
    /// Incoming call settings
    #[serde(rename = "incoming_call_flags")]
    pub incoming_call_flags: i32,
    /// Group DM add permissions
    #[serde(rename = "group_dm_add_permission_flags")]
    pub group_dm_add_permission_flags: i32,
    /// The folder structure for organizing guilds in the sidebar
    #[serde(rename = "guild_folders")]
    pub guild_folders: Vec<models::UserSettingsResponseGuildFoldersInner>,
    #[serde(rename = "custom_status", deserialize_with = "Option::deserialize")]
    pub custom_status: Option<Box<models::CustomStatusResponse>>,
    /// The idle timeout in seconds before going AFK
    #[serde(rename = "afk_timeout")]
    pub afk_timeout: i32,
    /// The preferred time format setting
    #[serde(rename = "time_format")]
    pub time_format: models::TimeFormatTypes,
    /// Whether developer mode is enabled
    #[serde(rename = "developer_mode")]
    pub developer_mode: bool,
    /// List of trusted external link domains
    #[serde(rename = "trusted_domains")]
    pub trusted_domains: Vec<String>,
    /// Whether muted channels are hidden by default in new guilds
    #[serde(rename = "default_hide_muted_channels")]
    pub default_hide_muted_channels: bool,
}

impl UserSettingsResponse {
    #[must_use]
    pub fn new(
        status: String,
        theme: String,
        locale: models::Locale,
        restricted_guilds: Vec<String>,
        bot_restricted_guilds: Vec<String>,
        default_guilds_restricted: bool,
        bot_default_guilds_restricted: bool,
        inline_attachment_media: bool,
        inline_embed_media: bool,
        gif_auto_play: bool,
        render_embeds: bool,
        render_reactions: bool,
        animate_emoji: bool,
        animate_stickers: models::StickerAnimationOptions,
        render_spoilers: models::RenderSpoilers,
        message_display_compact: bool,
        friend_source_flags: i32,
        incoming_call_flags: i32,
        group_dm_add_permission_flags: i32,
        guild_folders: Vec<models::UserSettingsResponseGuildFoldersInner>,
        custom_status: Option<models::CustomStatusResponse>,
        afk_timeout: i32,
        time_format: models::TimeFormatTypes,
        developer_mode: bool,
        trusted_domains: Vec<String>,
        default_hide_muted_channels: bool,
    ) -> UserSettingsResponse {
        UserSettingsResponse {
            status,
            status_resets_at: None,
            status_resets_to: None,
            theme,
            locale,
            restricted_guilds,
            bot_restricted_guilds,
            default_guilds_restricted,
            bot_default_guilds_restricted,
            inline_attachment_media,
            inline_embed_media,
            gif_auto_play,
            render_embeds,
            render_reactions,
            animate_emoji,
            animate_stickers,
            render_spoilers,
            message_display_compact,
            friend_source_flags,
            incoming_call_flags,
            group_dm_add_permission_flags,
            guild_folders,
            custom_status: custom_status.map(Box::new),
            afk_timeout,
            time_format,
            developer_mode,
            trusted_domains,
            default_hide_muted_channels,
        }
    }
}
