/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsUpdateRequest {
    /// Friend source flags
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::UserStatusType>,
    #[serde(
        rename = "status_resets_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_resets_at: Option<Option<Box<models::UserSettingsUpdateRequestStatusResetsAt>>>,
    #[serde(
        rename = "status_resets_to",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_resets_to: Option<Option<models::UserStatusType>>,
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<models::UserThemeType>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<models::Locale>,
    /// Guilds with DM restrictions
    #[serde(rename = "restricted_guilds", skip_serializing_if = "Option::is_none")]
    pub restricted_guilds: Option<Vec<String>>,
    /// Guilds with bot DM restrictions
    #[serde(
        rename = "bot_restricted_guilds",
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_restricted_guilds: Option<Vec<String>>,
    /// Default DM restriction for new guilds
    #[serde(
        rename = "default_guilds_restricted",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_guilds_restricted: Option<bool>,
    /// Default bot DM restriction for new guilds
    #[serde(
        rename = "bot_default_guilds_restricted",
        skip_serializing_if = "Option::is_none"
    )]
    pub bot_default_guilds_restricted: Option<bool>,
    /// Display attachments inline
    #[serde(
        rename = "inline_attachment_media",
        skip_serializing_if = "Option::is_none"
    )]
    pub inline_attachment_media: Option<bool>,
    /// Display embed media inline
    #[serde(rename = "inline_embed_media", skip_serializing_if = "Option::is_none")]
    pub inline_embed_media: Option<bool>,
    /// Auto-play GIFs
    #[serde(rename = "gif_auto_play", skip_serializing_if = "Option::is_none")]
    pub gif_auto_play: Option<bool>,
    /// Render message embeds
    #[serde(rename = "render_embeds", skip_serializing_if = "Option::is_none")]
    pub render_embeds: Option<bool>,
    /// Display reactions
    #[serde(rename = "render_reactions", skip_serializing_if = "Option::is_none")]
    pub render_reactions: Option<bool>,
    /// Animate custom emoji
    #[serde(rename = "animate_emoji", skip_serializing_if = "Option::is_none")]
    pub animate_emoji: Option<bool>,
    /// Sticker animation preference
    #[serde(rename = "animate_stickers", skip_serializing_if = "Option::is_none")]
    pub animate_stickers: Option<models::StickerAnimationOptions>,
    /// Spoiler rendering preference
    #[serde(rename = "render_spoilers", skip_serializing_if = "Option::is_none")]
    pub render_spoilers: Option<models::RenderSpoilers>,
    /// Compact message display
    #[serde(
        rename = "message_display_compact",
        skip_serializing_if = "Option::is_none"
    )]
    pub message_display_compact: Option<bool>,
    /// Friend source flags
    #[serde(
        rename = "friend_source_flags",
        skip_serializing_if = "Option::is_none"
    )]
    pub friend_source_flags: Option<i32>,
    /// Incoming call settings
    #[serde(
        rename = "incoming_call_flags",
        skip_serializing_if = "Option::is_none"
    )]
    pub incoming_call_flags: Option<i32>,
    /// Group DM add permissions
    #[serde(
        rename = "group_dm_add_permission_flags",
        skip_serializing_if = "Option::is_none"
    )]
    pub group_dm_add_permission_flags: Option<i32>,
    /// Guild folder organization
    #[serde(rename = "guild_folders", skip_serializing_if = "Option::is_none")]
    pub guild_folders: Option<Vec<models::UserSettingsUpdateRequestGuildFoldersInner>>,
    #[serde(
        rename = "custom_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub custom_status: Option<Option<Box<models::CustomStatusPayload>>>,
    /// AFK timeout in seconds
    #[serde(rename = "afk_timeout", skip_serializing_if = "Option::is_none")]
    pub afk_timeout: Option<i32>,
    /// Time format preference
    #[serde(rename = "time_format", skip_serializing_if = "Option::is_none")]
    pub time_format: Option<models::TimeFormatTypes>,
    /// Developer mode enabled
    #[serde(rename = "developer_mode", skip_serializing_if = "Option::is_none")]
    pub developer_mode: Option<bool>,
    /// Trusted external link domains. Use \"*\" to trust all domains.
    #[serde(rename = "trusted_domains", skip_serializing_if = "Option::is_none")]
    pub trusted_domains: Option<Vec<String>>,
    /// Hide muted channels by default in new guilds
    #[serde(
        rename = "default_hide_muted_channels",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_hide_muted_channels: Option<bool>,
}

impl UserSettingsUpdateRequest {
    #[must_use] 
    pub fn new() -> UserSettingsUpdateRequest {
        UserSettingsUpdateRequest {
            flags: None,
            status: None,
            status_resets_at: None,
            status_resets_to: None,
            theme: None,
            locale: None,
            restricted_guilds: None,
            bot_restricted_guilds: None,
            default_guilds_restricted: None,
            bot_default_guilds_restricted: None,
            inline_attachment_media: None,
            inline_embed_media: None,
            gif_auto_play: None,
            render_embeds: None,
            render_reactions: None,
            animate_emoji: None,
            animate_stickers: None,
            render_spoilers: None,
            message_display_compact: None,
            friend_source_flags: None,
            incoming_call_flags: None,
            group_dm_add_permission_flags: None,
            guild_folders: None,
            custom_status: None,
            afk_timeout: None,
            time_format: None,
            developer_mode: None,
            trusted_domains: None,
            default_hide_muted_channels: None,
        }
    }
}
