/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `UserThemeType` : UI theme preference
/// UI theme preference
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum UserThemeType {
    #[serde(rename = "dark")]
    #[default]
    Dark,
    #[serde(rename = "coal")]
    Coal,
    #[serde(rename = "light")]
    Light,
    #[serde(rename = "system")]
    System,
}

impl std::fmt::Display for UserThemeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dark => write!(f, "dark"),
            Self::Coal => write!(f, "coal"),
            Self::Light => write!(f, "light"),
            Self::System => write!(f, "system"),
        }
    }
}
