/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `UserStatusType` : User online status
/// User online status
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum UserStatusType {
    #[serde(rename = "online")]
    #[default]
    Online,
    #[serde(rename = "dnd")]
    Dnd,
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "invisible")]
    Invisible,
}

impl std::fmt::Display for UserStatusType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Online => write!(f, "online"),
            Self::Dnd => write!(f, "dnd"),
            Self::Idle => write!(f, "idle"),
            Self::Invisible => write!(f, "invisible"),
        }
    }
}
