/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCreateRequest {
    /// The name of the webhook
    #[serde(rename = "name")]
    pub name: String,
    /// Base64-encoded image data
    #[serde_as(as = "super::DoubleOption<serde_with::base64::Base64>")]
    #[serde(rename = "avatar", default, skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<Vec<u8>>>,
}

impl WebhookCreateRequest {
    #[must_use]
    pub fn new(name: String) -> WebhookCreateRequest {
        WebhookCreateRequest { name, avatar: None }
    }
}
