/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `WellKnownFluxerResponseEndpoints` : Endpoint URLs for various services
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownFluxerResponseEndpoints {
    /// Base URL for authenticated API requests
    #[serde(rename = "api")]
    pub api: String,
    /// Base URL for client API requests
    #[serde(rename = "api_client")]
    pub api_client: String,
    /// Base URL for public API requests
    #[serde(rename = "api_public")]
    pub api_public: String,
    /// WebSocket URL for the gateway
    #[serde(rename = "gateway")]
    pub gateway: String,
    /// Base URL for the media proxy
    #[serde(rename = "media")]
    pub media: String,
    /// Base URL for static assets (avatars, emojis, etc.)
    #[serde(rename = "static_cdn")]
    pub static_cdn: String,
    /// Base URL for the marketing website
    #[serde(rename = "marketing")]
    pub marketing: String,
    /// Base URL for the admin panel
    #[serde(rename = "admin")]
    pub admin: String,
    /// Base URL for invite links
    #[serde(rename = "invite")]
    pub invite: String,
    /// Base URL for gift links
    #[serde(rename = "gift")]
    pub gift: String,
    /// Base URL for the web application
    #[serde(rename = "webapp")]
    pub webapp: String,
}

impl WellKnownFluxerResponseEndpoints {
    /// Endpoint URLs for various services
    #[must_use] 
    pub fn new(
        api: String,
        api_client: String,
        api_public: String,
        gateway: String,
        media: String,
        static_cdn: String,
        marketing: String,
        admin: String,
        invite: String,
        gift: String,
        webapp: String,
    ) -> WellKnownFluxerResponseEndpoints {
        WellKnownFluxerResponseEndpoints {
            api,
            api_client,
            api_public,
            gateway,
            media,
            static_cdn,
            marketing,
            admin,
            invite,
            gift,
            webapp,
        }
    }
}
