/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `WellKnownFluxerResponseFederation` : Federation configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownFluxerResponseFederation {
    /// Whether federation is enabled on this instance
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Federation protocol version
    #[serde(rename = "version")]
    pub version: i32,
}

impl WellKnownFluxerResponseFederation {
    /// Federation configuration
    #[must_use]
    pub fn new(enabled: bool, version: i32) -> WellKnownFluxerResponseFederation {
        WellKnownFluxerResponseFederation { enabled, version }
    }
}
