/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `WellKnownFluxerResponsePush` : Push notification configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownFluxerResponsePush {
    #[serde(rename = "public_vapid_key", deserialize_with = "Option::deserialize")]
    pub public_vapid_key: Option<String>,
}

impl WellKnownFluxerResponsePush {
    /// Push notification configuration
    #[must_use]
    pub fn new(public_vapid_key: Option<String>) -> WellKnownFluxerResponsePush {
        WellKnownFluxerResponsePush { public_vapid_key }
    }
}
