/*
 * Fluxer API
 *
 * API for Fluxer, a free and open source instant messaging and VoIP platform built for friends, groups, and communities.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: developers@fluxer.app
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// `WellKnownFluxerResponseSso` : Single sign-on configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WellKnownFluxerResponseSso {
    /// Whether SSO is enabled for this instance
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Whether SSO is required for all users
    #[serde(rename = "enforced")]
    pub enforced: bool,
    #[serde(rename = "display_name", deserialize_with = "Option::deserialize")]
    pub display_name: Option<String>,
    /// OAuth redirect URI for SSO
    #[serde(rename = "redirect_uri")]
    pub redirect_uri: String,
}

impl WellKnownFluxerResponseSso {
    /// Single sign-on configuration
    #[must_use]
    pub fn new(
        enabled: bool,
        enforced: bool,
        display_name: Option<String>,
        redirect_uri: String,
    ) -> WellKnownFluxerResponseSso {
        WellKnownFluxerResponseSso {
            enabled,
            enforced,
            display_name,
            redirect_uri,
        }
    }
}
